// Provider calls are intentionally mocked: no real credentials or network usage.
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {fixtures} from './fixtures.mjs';
import {id} from '../public/modules/core.mjs';
process.env.DATABASE_MODE='sqlite';process.env.DATABASE_PATH=':memory:';process.env.SEED_SAMPLE_DATA='false';
process.env.BOOTSTRAP_ADMIN_EMAIL='ai-test@example.test';process.env.BOOTSTRAP_ADMIN_PASSWORD='AI-Test-Password-123!';
process.env.APP_URL='http://localhost:3000';process.env.AI_REPORTS_ENABLED='true';process.env.OPENAI_API_KEY='test-key-not-a-real-credential';process.env.OPENAI_MODEL='unit-test-model';process.env.GEMINI_API_KEY='test-gemini-key-not-a-real-credential';
const {handleApi,repository}=await import('../server/service.mjs');
const f=fixtures();f.trainee.trainee_name='Private Test Name';f.trainee.email='private@example.test';f.assessment.instructor_comment='PRIVATE COMMENT MUST NOT BE SENT';
let token,user,repo;const realFetch=globalThis.fetch;
before(async()=>{repo=await repository();await repo.setup({token:repo.setupToken,email:process.env.BOOTSTRAP_ADMIN_EMAIL,full_name:'AI Test Administrator',password:process.env.BOOTSTRAP_ADMIN_PASSWORD});repo.insert('companies',f.company);repo.insert('batches',f.batch);repo.insert('trainees',f.trainee);repo.insert('attendance_10day',f.summary);repo.insert('assessments',f.assessment);({token,user}=await repo.login(process.env.BOOTSTRAP_ADMIN_EMAIL,process.env.BOOTSTRAP_ADMIN_PASSWORD));});
after(()=>{globalThis.fetch=realFetch;repo.close();});
async function run(body={traineeId:f.trainee.id,kind:'assessment',consent:true}){const response=await handleApi(new Request('http://localhost:3000/api/ai',{method:'POST',headers:{origin:'http://localhost:3000','x-red-request':'1',cookie:'red_session='+token,'Content-Type':'application/json'},body:JSON.stringify(body)}));return {status:response.status,data:await response.json()};}
const studioDraftRequest={kind:'draft-studio-challenge',consent:true,title:'Discovery Practice',category:'Client discovery',level:'Core',duration_minutes:8,description:'Ask purposeful questions before recommending.',lesson_notes:'Practice open questions, listening, and a clear next step.',round_count:3};
const sessionPromptRequest={kind:'draft-session-prompts',consent:true,focus_skill:'discovery',activity_id:'quiz-discovery',lesson_notes:'Revisit open questions and the client’s timeline before suggesting a property.'};
function generatedStudioDraft(){return {questions:Array.from({length:3},(_,index)=>({prompt:`A client describes a broad goal. What is the best next move in round ${index+1}?`,options:['Send several generic options.','Ask a focused open question and listen.','Promise an outcome before checking details.','Select the client priority for them.'],answer:1,skill:'discovery',hint:'First learn what matters most.',explanation:'A focused question reveals the client goal before you make a relevant recommendation.'})),study_cards:[{front:'What comes before a recommendation?',back:'Understand the client goal, timing, and priorities first.'}]};}
function generatedSessionPrompts(){return {spark:'Recall a question that helped a client explain why they are moving.',quest:'Play the challenge together. Commit to a choice before the trainer reveals the coaching takeaway.',huddle:'Which response protected the client’s goal, and what would you say in a real conversation?',exit:'Name one open question you will use in your next client conversation.'};}
const roleplayDraftRequest={kind:'draft-roleplay-scenario',consent:true,focus_skill:'discovery',lesson_notes:'Practise checking a client’s timing before suggesting a next step.'};
function generatedRoleplayDraft(){return {title:'The rushed move',level:'Core',setup:'A client wants to move soon but has not explained the timing.',trainer_brief:'The client has a flexible move window and values a short commute. Reveal those details only if asked.',turns:[{client_line:'I need to move soon, but I’m not sure where to start.',coach_cue:'Ask what is driving the move and give the client time to explain.'},{client_line:'I have a few options in mind. Can you tell me which is best?',coach_cue:'Clarify their priorities before comparing options; do not choose for them.'},{client_line:'That makes sense. What would you suggest we do next?',coach_cue:'Reflect the client’s priority and agree a specific, client-approved next step.'}],look_fors:[{label:'Asks an open question before recommending'},{label:'Checks the client’s priority in their own words'},{label:'Agrees a clear next step with the client'}],avoid:'Do not promise an outcome, invent availability, or rush the client into a decision.',model:'I can help compare the options against what matters most to you. What would make a move feel manageable?',debrief:'Which question helped the client explain what mattered most?'};}
test('AI requires explicit consent and makes no provider call without it',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run({traineeId:f.trainee.id,kind:'assessment',consent:false})).status,400);assert.equal(called,false);});
test('Provider request excludes names, contact details and instructor comments',async()=>{let payload;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');payload=JSON.parse(options.body);return Response.json({output:[{content:[{type:'output_text',text:'A reviewed training draft.'}]}]});};const r=await run();assert.equal(r.status,200);assert.equal(r.data.source,'ai');assert.equal(r.data.report,'A reviewed training draft.');assert.equal(payload.store,false);assert.equal(payload.model,'unit-test-model');assert.equal(payload.max_output_tokens,650);for(const secret of [f.trainee.trainee_name,f.trainee.email,f.assessment.instructor_comment,f.trainee.id])assert.ok(!JSON.stringify(payload).includes(secret));});
test('AI comment polishing requires consent and sends only the comment draft to Gemini',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run({kind:'polish-comment',comment:'A draft comment.',consent:false})).status,400);assert.equal(called,false);let payload;globalThis.fetch=async(url,options)=>{assert.match(url,/generativelanguage\.googleapis\.com\/v1beta\/models\/gemini-2\.5-flash-lite:generateContent/);payload=JSON.parse(options.body);return Response.json({candidates:[{content:{parts:[{text:'A polished instructor comment.'}]}}]});};const r=await run({kind:'polish-comment',comment:'A draft comment.',consent:true});assert.equal(r.status,200);assert.equal(r.data.comment,'A polished instructor comment.');assert.deepEqual(JSON.parse(payload.contents[0].parts[0].text),{draft:'A draft comment.'});assert.equal(payload.generationConfig.maxOutputTokens,500);for(const secret of [f.trainee.trainee_name,f.trainee.email,f.assessment.instructor_comment,f.trainee.id])assert.ok(!JSON.stringify(payload).includes(secret));assert.equal((await repo.state(user)).assessments[0].instructor_comment,f.assessment.instructor_comment);});
test('AI comment polishing stays disabled when the Gemini secret is missing',async()=>{const key=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;try{assert.equal((await run({kind:'polish-comment',comment:'A draft comment.',consent:true})).status,503);}finally{process.env.GEMINI_API_KEY=key;}});
test('AI challenge drafting requires explicit consent and refuses contact details before any provider call',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run({...studioDraftRequest,consent:false})).status,400);assert.equal((await run({...studioDraftRequest,lesson_notes:'Call trainer@example.test at 123-456-7890'})).status,400);assert.equal((await run({...studioDraftRequest,description:'Contact trainer@example.test for details'})).status,400);assert.equal(called,false);});
test('AI challenge drafts use structured Gemini JSON, contain no trainee records, and remain unsaved until a trainer publishes',async()=>{let payload;const before=repo.customChallenges().length;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent');assert.equal(options.headers['x-goog-api-key'],'test-gemini-key-not-a-real-credential');assert.ok(!url.includes('test-gemini'));payload=JSON.parse(options.body);return Response.json({candidates:[{content:{parts:[{text:JSON.stringify(generatedStudioDraft())}]}}]});};const response=await run(studioDraftRequest);assert.equal(response.status,200);assert.equal(response.data.source,'ai');assert.equal(response.data.questions.length,3);assert.equal(response.data.study_cards.length,1);assert.equal(payload.generationConfig.responseFormat.text.mimeType,'application/json');assert.equal(payload.generationConfig.responseFormat.text.schema.properties.questions.minItems,3);const prompt=payload.contents[0].parts[0].text;for(const secret of [f.trainee.trainee_name,f.trainee.email,f.assessment.instructor_comment,f.trainee.id])assert.ok(!prompt.includes(secret));assert.deepEqual(JSON.parse(prompt).trainer_notes,studioDraftRequest.lesson_notes);assert.equal(repo.customChallenges().length,before);});
test('AI challenge output is validated and rejected safely instead of publishing a malformed draft',async()=>{globalThis.fetch=async()=>Response.json({candidates:[{content:{parts:[{text:JSON.stringify({questions:[],study_cards:[]})}]}}]});const result=await run(studioDraftRequest);assert.equal(result.status,502);assert.match(result.data.error,/did not pass challenge validation/);});
test('AI challenge drafting remains unavailable without the existing Gemini configuration',async()=>{const enabled=process.env.AI_REPORTS_ENABLED,key=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;try{assert.equal((await run(studioDraftRequest)).status,503);}finally{process.env.AI_REPORTS_ENABLED=enabled;process.env.GEMINI_API_KEY=key;}});
test('AI challenge drafting has a separate per-user hourly budget before provider calls',async()=>{for(let i=0;i<6;i++)await repo.rate('ai-studio-draft:'+user.id,6,3600,token);let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run(studioDraftRequest)).status,429);assert.equal(called,false);});
test('AI session co-planner requires consent and refuses personal contact details without a provider call',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run({...sessionPromptRequest,consent:false})).status,400);assert.equal((await run({...sessionPromptRequest,lesson_notes:'Email coach@example.test'})).status,400);assert.equal((await run({...sessionPromptRequest,lesson_notes:'Call +20 (123) 456-7890'})).status,400);assert.equal(called,false);});
test('AI session co-planner drafts four unsaved cues and shares only safe challenge metadata and consented notes',async()=>{let payload;const plansBefore=(await repo.activitySessionPlans()).plans.length;globalThis.fetch=async(url,options)=>{assert.match(url,/generativelanguage\.googleapis\.com\/v1beta\/models\/gemini-2\.5-flash-lite:generateContent/);payload=JSON.parse(options.body);return Response.json({candidates:[{content:{parts:[{text:JSON.stringify(generatedSessionPrompts())}]}}]});};const result=await run(sessionPromptRequest);assert.equal(result.status,200);assert.deepEqual(result.data.step_prompts,generatedSessionPrompts());assert.equal(result.data.source,'ai');assert.deepEqual(JSON.parse(payload.contents[0].parts[0].text),{learning_focus:'Client discovery',challenge:{title:'Discovery Sprint',category:'Client discovery',description:'A fast team warm-up for asking better questions before recommending a property.',duration_minutes:5},trainer_notes:sessionPromptRequest.lesson_notes,required_steps:['spark','quest','huddle','exit']});assert.equal(payload.generationConfig.responseFormat.text.mimeType,'application/json');for(const secret of [f.trainee.trainee_name,f.trainee.email,f.assessment.instructor_comment,f.trainee.id,'correct answer'])assert.ok(!JSON.stringify(payload).includes(secret));assert.equal((await repo.activitySessionPlans()).plans.length,plansBefore);});
test('AI session co-planner rejects incomplete generated prompts and enforces its own hourly limit',async()=>{globalThis.fetch=async()=>Response.json({candidates:[{content:{parts:[{text:JSON.stringify({spark:'Only one cue is not a complete session.'})}]}}]});const malformed=await run(sessionPromptRequest);assert.equal(malformed.status,502);for(let i=0;i<8;i++)await repo.rate('ai-session-plan:'+user.id,8,3600,token);let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};const limited=await run(sessionPromptRequest);assert.equal(limited.status,429);assert.equal(called,false);});
test('AI role-play co-planner requires consent and rejects contact details before any provider request',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run({...roleplayDraftRequest,consent:false})).status,400);assert.equal((await run({...roleplayDraftRequest,lesson_notes:'Email client@example.test'})).status,400);assert.equal((await run({...roleplayDraftRequest,lesson_notes:'Call +20 (123) 456-7890'})).status,400);assert.equal(called,false);});
test('AI role-play draft returns three validated turns and coaching moves without including roster data or saving anything',async()=>{let payload;const before=await repo.state(user);globalThis.fetch=async(url,options)=>{assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent');assert.equal(options.headers['x-goog-api-key'],'test-gemini-key-not-a-real-credential');payload=JSON.parse(options.body);return Response.json({candidates:[{content:{parts:[{text:JSON.stringify(generatedRoleplayDraft())}]}}]});};const result=await run(roleplayDraftRequest);assert.equal(result.status,200);assert.equal(result.data.source,'ai');assert.equal(result.data.scenario.id,'ai-draft');assert.equal(result.data.scenario.turns.length,3);assert.equal(result.data.scenario.lookFors.length,3);assert.equal(payload.generationConfig.responseFormat.text.mimeType,'application/json');assert.equal(payload.generationConfig.responseFormat.text.schema.properties.turns.minItems,3);assert.equal(payload.generationConfig.responseFormat.text.schema.properties.look_fors.maxItems,3);const prompt=payload.contents[0].parts[0].text;assert.deepEqual(JSON.parse(prompt),{learning_focus:'Client discovery',trainer_lesson_notes:roleplayDraftRequest.lesson_notes,exact_client_turns:3,exact_coaching_moves:3,mode:'spoken classroom practice only; ungraded, no transcript or trainee data'});for(const secret of [f.trainee.trainee_name,f.trainee.email,f.assessment.instructor_comment,f.trainee.id])assert.ok(!JSON.stringify(payload).includes(secret));assert.deepEqual(await repo.state(user),before);});
test('AI role-play output failing the strict classroom schema is not returned as usable content',async()=>{globalThis.fetch=async()=>Response.json({candidates:[{content:{parts:[{text:JSON.stringify({...generatedRoleplayDraft(),turns:[]})}]}}]});const result=await run(roleplayDraftRequest);assert.equal(result.status,502);assert.match(result.data.error,/did not pass safety and classroom-quality checks/);});
test('AI role-play drafts stay disabled without Gemini configuration and have an independent hourly limit',async()=>{const key=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;try{assert.equal((await run(roleplayDraftRequest)).status,503);}finally{process.env.GEMINI_API_KEY=key;}for(let i=0;i<6;i++)await repo.rate('ai-roleplay-draft:'+user.id,6,3600,token);let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected provider call');};assert.equal((await run(roleplayDraftRequest)).status,429);assert.equal(called,false);});
test('AI generation does not silently save or overwrite an assessment',async()=>{assert.equal((await repo.state(user)).assessments[0].report,'');assert.equal((await repo.state(user)).assessments[0].version,1);});
test('Provider errors return a clear failure without changing saved data',async()=>{globalThis.fetch=async()=>new Response('{}',{status:500,headers:{'Content-Type':'application/json'}});assert.equal((await run()).status,502);assert.equal((await repo.state(user)).assessments[0].report,'');});
test('Empty provider output is rejected',async()=>{globalThis.fetch=async()=>Response.json({output:[]});assert.equal((await run()).status,502);});
test('An unknown trainee cannot trigger a provider call',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected call');};assert.equal((await run({traineeId:id(),kind:'attendance',consent:true})).status,404);assert.equal(called,false);});
test('Per-user report budget is enforced before calling the provider',async()=>{for(let i=0;i<10;i++)await repo.rate('ai:'+user.id,10,3600);let called=false;globalThis.fetch=async()=>{called=true;throw new Error('Unexpected call');};assert.equal((await run()).status,429);assert.equal(called,false);});
