import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {id,sessionDates,today} from '../public/modules/core.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'red-academy-api-'));
process.env.DATABASE_MODE='sqlite';process.env.DATABASE_PATH=path.join(dir,'api.db');process.env.SEED_SAMPLE_DATA='false';
process.env.BOOTSTRAP_ADMIN_EMAIL='admin@example.test';process.env.BOOTSTRAP_ADMIN_PASSWORD='API-Test-Password-123!';
process.env.APP_URL='http://localhost:3000';delete process.env.APP_ENV;delete process.env.OPENAI_API_KEY;delete process.env.OPENAI_MODEL;
const {handleApi,repository}=await import('../server/service.mjs');
let adminCookie='',viewerCookie='',instructorCookie='',company,batch,trainee;
async function request(route,{method='GET',body,cookie='',origin=process.env.APP_URL,custom=true,raw}={}){
 const headers=new Headers();if(cookie)headers.set('cookie',cookie);if(method!=='GET'){headers.set('content-type','application/json');if(origin)headers.set('origin',origin);if(custom)headers.set('x-red-request','1');}
 const response=await handleApi(new Request(process.env.APP_URL+'/api/'+route,{method,headers,...(method!=='GET'?{body:raw??JSON.stringify(body||{})}:{})}));
 const data=response.headers.get('content-type')?.includes('application/json')?await response.json():null;
 return {response,data,status:response.status,cookie:response.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};
}
before(async()=>{const repo=await repository();await repo.setup({token:repo.setupToken,email:'admin@example.test',full_name:'Test Administrator',password:process.env.BOOTSTRAP_ADMIN_PASSWORD});const login=await request('auth/login',{method:'POST',body:{email:'admin@example.test',password:process.env.BOOTSTRAP_ADMIN_PASSWORD}});assert.equal(login.status,200);adminCookie=login.cookie;assert.equal((await request('state',{cookie:adminCookie})).data.companies.length,0);company=(await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'companies',action:'create',data:{name:'API Company'}}})).data.records[0];
 for(const role of ['viewer','instructor']){
  const invite=await request('invitations',{method:'POST',cookie:adminCookie,body:{email:role+'@example.test',full_name:role,role}});assert.equal(invite.status,201);assert.equal((await request('auth/accept-invitation',{method:'POST',body:{token:invite.data.token,password:'API-Test-Password-123!',role:'admin'}})).status,201);
  const list=await request('users',{cookie:adminCookie});const user=list.data.find(u=>u.email===role+'@example.test');
  assert.equal((await request('users',{method:'PATCH',cookie:adminCookie,body:{id:user.id,role,active:true}})).status,200);
  const login=await request('auth/login',{method:'POST',body:{email:user.email,password:'API-Test-Password-123!'}});
  if(role==='viewer')viewerCookie=login.cookie;else instructorCookie=login.cookie;
 }
 const b=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'batches',action:'create',data:{batch_name:'API Batch',status:'Active',start_date:'2026-09-06',end_date:'2026-09-19',session_dates:sessionDates('2026-09-06'),capacity:20,description:''}}});assert.equal(b.status,200);batch=b.data.records[0];
 const t=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'create',data:{trainee_name:'API Trainee',company_id:company.id,batch_id:batch.id,email:'',phone:'',job_title:'',notes:''}}});assert.equal(t.status,200);assert.equal(t.data.records.length,2);trainee=t.data.records[0];assert.equal(trainee.enrollment_status,'Active');
});
after(async()=>{(await repository()).close();fs.rmSync(dir,{recursive:true,force:true});});
test('Unauthenticated session is public; private data returns 401',async()=>{assert.equal((await request('session')).data.user,null);assert.equal((await request('state')).status,401);});
test('Session cookie is opaque, HttpOnly and SameSite=Lax',async()=>{const r=await request('auth/login',{method:'POST',body:{email:'admin@example.test',password:process.env.BOOTSTRAP_ADMIN_PASSWORD}});const cookie=r.response.headers.getSetCookie()[0];assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Lax/);assert.ok(!cookie.includes('admin@example'));});
test('Wrong Origin and missing custom header are blocked',async()=>{assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,origin:'https://evil.example',body:{}})).status,403);assert.equal((await request('auth/login',{method:'POST',custom:false,body:{}})).status,403);});
test('Malformed and non-object JSON bodies return 400, not a server crash',async()=>{for(const raw of ['{bad','null','[]','4'])assert.equal((await request('auth/login',{method:'POST',raw})).status,400);});
test('Public registration is disabled and cannot create accounts',async()=>{const email='pending@example.test';assert.equal((await request('auth/register',{method:'POST',body:{email,password:'API-Test-Password-123!',full_name:'Pending',role:'admin',active:true}})).status,403);assert.equal((await request('auth/login',{method:'POST',body:{email,password:'API-Test-Password-123!'}})).status,401);});
test('Viewer reads but cannot write or administer accounts',async()=>{assert.equal((await request('state',{cookie:viewerCookie})).status,200);assert.equal((await request('mutate',{method:'POST',cookie:viewerCookie,body:{table:'companies',action:'create',data:{name:'Forbidden'}}})).status,403);assert.equal((await request('users',{cookie:viewerCookie})).status,403);assert.equal((await request('users',{method:'PATCH',cookie:viewerCookie,body:{id:trainee.id,role:'admin',active:true}})).status,403);});
test('Live facilitator answer keys are private to writable staff',async()=>{assert.equal((await request('activities/facilitator-deck')).status,401);assert.equal((await request('activities/facilitator-deck',{cookie:viewerCookie})).status,403);const trainer=await request('activities/facilitator-deck',{cookie:instructorCookie});assert.equal(trainer.status,200);assert.ok(trainer.data.activities[0].questions[0].explanation);assert.ok(Number.isInteger(trainer.data.activities[0].questions[0].answer));const publicLibrary=await request('activities/library',{cookie:viewerCookie});assert.equal(publicLibrary.status,200);assert.ok(publicLibrary.data.activities.every(activity=>!('questions'in activity)&&!('answer'in activity)));});
test('Admins can correct a staff display name without changing access or ending its session',async()=>{const member=(await request('users',{cookie:adminCookie})).data.find(user=>user.email==='viewer@example.test');assert.ok(member);assert.equal((await request('users/profile',{method:'PATCH',cookie:viewerCookie,body:{id:member.id,full_name:'Viewer Unauthorized'}})).status,403);for(const full_name of ['', 'x'.repeat(161), 'Invalid\nName'])assert.equal((await request('users/profile',{method:'PATCH',cookie:adminCookie,body:{id:member.id,full_name}})).status,400);const changed=await request('users/profile',{method:'PATCH',cookie:adminCookie,body:{id:member.id,full_name:'Viewer Updated'}});assert.equal(changed.status,200);const saved=(await request('users',{cookie:adminCookie})).data.find(user=>user.id===member.id);assert.equal(saved.full_name,'Viewer Updated');assert.equal(saved.role,'viewer');assert.equal(saved.active,true);assert.equal((await request('session',{cookie:viewerCookie})).data.user.full_name,'Viewer Updated');assert.ok((await request('state',{cookie:adminCookie})).data.audit_log.some(row=>row.action==='display-name'&&row.entity_id===member.id));});
test('Batch archive is admin-only, audited, reversible, and leaves linked records intact',async()=>{
 assert.equal((await request('batches/archive',{method:'POST',body:{id:batch.id,expectedVersion:batch.version,archived:true}})).status,401);
 assert.equal((await request('batches/archive',{method:'POST',cookie:viewerCookie,body:{id:batch.id,expectedVersion:batch.version,archived:true}})).status,403);
 assert.equal((await request('batches/archive',{method:'POST',cookie:instructorCookie,body:{id:batch.id,expectedVersion:batch.version,archived:true}})).status,403);
 const archived=await request('batches/archive',{method:'POST',cookie:adminCookie,body:{id:batch.id,expectedVersion:batch.version,archived:true}});assert.equal(archived.status,200);assert.ok(archived.data.record.archived_at);assert.equal(archived.data.record.archived_by,'admin@example.test');
 const state=await request('state',{cookie:adminCookie});assert.ok(state.data.batches.some(row=>row.id===batch.id&&row.archived_at));assert.ok(state.data.trainees.some(row=>row.id===trainee.id));
 assert.equal((await request('batches/archive',{method:'POST',cookie:adminCookie,body:{id:batch.id,expectedVersion:batch.version,archived:false}})).status,409);
 const restored=await request('batches/archive',{method:'POST',cookie:adminCookie,body:{id:batch.id,expectedVersion:archived.data.record.version,archived:false}});assert.equal(restored.status,200);assert.equal(restored.data.record.archived_at,null);assert.equal(restored.data.record.archived_by,null);
 assert.equal((await request('batches/archive',{method:'POST',cookie:adminCookie,body:{id:'not-a-uuid',expectedVersion:1,archived:true}})).status,400);
});
test('Instructor can create records but cannot delete company records',async()=>{const r=await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'companies',action:'create',data:{name:'Instructor Company'}}});assert.equal(r.status,200);assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'companies',action:'delete',id:r.data.records[0].id,expectedVersion:1}})).status,403);});
test('Instructor can delete operational batches and trainees',async()=>{
 const batchResponse=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'batches',action:'create',data:{batch_name:'Instructor Delete Batch',status:'Planning',start_date:'2026-10-01',end_date:'2026-10-14',session_dates:sessionDates('2026-10-01'),capacity:10,description:''}}});assert.equal(batchResponse.status,200,JSON.stringify(batchResponse.data));const newBatch=batchResponse.data.records[0];
 const traineeResponse=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'create',data:{trainee_name:'Instructor Delete Trainee',company_id:company.id,batch_id:newBatch.id,email:'',phone:'',job_title:'',notes:''}}});assert.equal(traineeResponse.status,200,JSON.stringify(traineeResponse.data));const newTrainee=traineeResponse.data.records[0];
 assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'trainees',action:'delete',id:newTrainee.id,expectedVersion:newTrainee.version}})).status,200);
 assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'batches',action:'delete',id:newBatch.id,expectedVersion:newBatch.version}})).status,200);
});
test('Activity assignments use the authenticated Academy roster and are shared immediately',async()=>{
 assert.equal((await request('activities')).status,401);
 const created=await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{batch_id:batch.id,activity_id:'rapidfire',instructions:'Focus on concise discovery questions.',due_date:'2026-09-30',trainee_ids:[trainee.id]}});
 assert.equal(created.status,201,JSON.stringify(created.data));
 assert.equal(created.data.record.title,'Rapid Fire');
 assert.equal(created.data.record.created_by,'instructor@example.test');
 const adminView=await request('activities',{cookie:adminCookie});
 const assignment=adminView.data.assignments.find(row=>row.id===created.data.record.id);
 assert.equal(assignment.batch_name,'API Batch');assert.equal(assignment.participants[0].trainee_id,trainee.id);assert.equal(assignment.participants[0].trainee_name,'API Trainee');
 assert.equal((await request('activities/assign',{method:'POST',cookie:viewerCookie,body:{batch_id:batch.id,activity_id:'rapidfire',trainee_ids:[trainee.id]}})).status,403);
 const update=await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:assignment.id,trainee_id:trainee.id,expected_version:1,status:'Completed',score:87.5,trainer_feedback:'Strong discovery; add one follow-up question.'}});
 assert.equal(update.status,200,JSON.stringify(update.data));assert.equal(update.data.record.score,87.5);assert.ok(update.data.record.completed_at);
 const latest=(await request('activities',{cookie:adminCookie})).data.assignments.find(row=>row.id===assignment.id);
 assert.equal(latest.participants[0].status,'Completed');assert.equal(latest.participants[0].trainer_feedback,'Strong discovery; add one follow-up question.');
 assert.equal((await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:assignment.id,trainee_id:trainee.id,expected_version:1,status:'In Progress',score:null,trainer_feedback:''}})).status,409);
 const closed=await request('activities/close',{method:'POST',cookie:instructorCookie,body:{id:assignment.id,expected_version:1,status:'Closed'}});
 assert.equal(closed.status,200);assert.equal(closed.data.record.status,'Closed');
 assert.equal((await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:assignment.id,trainee_id:trainee.id,expected_version:2,status:'In Progress',score:null,trainer_feedback:''}})).status,409);
});
test('Activity assignment rejects unknown library items, cross-batch trainees, and unsafe scores',async()=>{
 const base={batch_id:batch.id,activity_id:'rapidfire',trainee_ids:[trainee.id]};
 assert.equal((await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{...base,activity_id:'not-a-real-activity'}})).status,400);
 assert.equal((await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{...base,trainee_ids:['00000000-0000-4000-8000-000000000000']}})).status,400);
 assert.equal((await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:'00000000-0000-4000-8000-000000000000',trainee_id:trainee.id,expected_version:1,status:'Completed',score:101,trainer_feedback:''}})).status,400);
});
test('Shared classroom session plans persist run-of-show progress across trainers with version conflicts protected',async()=>{
 assert.equal((await request('activities/session-plans')).status,401);
 assert.equal((await request('activities/session-plans',{cookie:'red_session=invalid'})).status,401);
 assert.equal((await request('activities/session-plans',{cookie:viewerCookie})).status,403);
 const body={batch_id:batch.id,company_id:company.id,session_date:'2026-10-06',title:'Discovery and trust lab',focus_skill:'discovery',duration_minutes:30,activity_id:'quiz-discovery'};
 assert.equal((await request('activities/session-plans',{method:'POST',cookie:viewerCookie,body})).status,403);
 assert.equal((await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body:{...body,session_date:'2026-02-31'}})).status,400);
 assert.equal((await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body:{...body,company_id:id()}})).status,400);
 assert.equal((await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body:{...body,duration_minutes:12}})).status,400);
 const created=await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body});
 assert.equal(created.status,201,JSON.stringify(created.data));
 const plan=created.data.record;
 assert.equal(plan.batch_id,batch.id);assert.equal(plan.batch_name,'API Batch');
 assert.equal(plan.company_id,company.id);assert.equal(plan.company_name,'API Company');
 assert.equal(plan.status,'Planned');assert.equal(plan.version,1);assert.equal(plan.outline.length,4);
 assert.deepEqual(plan.outline.map(step=>step.id),['spark','quest','huddle','exit']);
 const shared=(await request('activities/session-plans',{cookie:adminCookie}));
 assert.equal(shared.status,200);assert.equal(shared.data.skills.length,8);
 assert.equal(shared.data.plans.find(row=>row.id===plan.id).title,plan.title);
 assert.equal((await request('activities/session-plans/step',{method:'PATCH',cookie:viewerCookie,body:{id:plan.id,expected_version:1,step_id:'spark',completed:true}})).status,403);
 const first=await request('activities/session-plans/step',{method:'PATCH',cookie:instructorCookie,body:{id:plan.id,expected_version:1,step_id:'spark',completed:true}});
 assert.equal(first.status,200,JSON.stringify(first.data));assert.equal(first.data.record.status,'In Progress');assert.equal(first.data.record.version,2);
 assert.equal((await request('activities/session-plans/step',{method:'PATCH',cookie:adminCookie,body:{id:plan.id,expected_version:1,step_id:'quest',completed:true}})).status,409);
 let version=2;
 for(const step_id of ['quest','huddle','exit']){
  const updated=await request('activities/session-plans/step',{method:'PATCH',cookie:adminCookie,body:{id:plan.id,expected_version:version,step_id,completed:true}});
  assert.equal(updated.status,200,JSON.stringify(updated.data));version++;
 }
 let complete=(await request('activities/session-plans',{cookie:instructorCookie})).data.plans.find(row=>row.id===plan.id);
 assert.equal(complete.status,'Completed');assert.equal(complete.version,5);assert.ok(complete.completed_at);assert.ok(complete.outline.every(step=>step.done));
 const reopened=await request('activities/session-plans/step',{method:'PATCH',cookie:instructorCookie,body:{id:plan.id,expected_version:5,step_id:'exit',completed:false}});
 assert.equal(reopened.status,200);assert.equal(reopened.data.record.status,'In Progress');assert.equal(reopened.data.record.completed_at,null);
 const audit=(await request('state',{cookie:adminCookie})).data.audit_log;
 assert.ok(audit.some(row=>row.action==='create-activity-session-plan'&&row.entity_id===plan.id));
 assert.ok(audit.some(row=>row.action==='complete-activity-session-step'&&row.entity_id===plan.id));
});
test('A session follow-up quiz unlocks on Cairo date, links once under concurrent trainers, and stays shared',async()=>{
 const futureDate=today(new Date(Date.now()+3*86400000));
 const base={batch_id:batch.id,company_id:company.id,focus_skill:'discovery',duration_minutes:30,activity_id:'quiz-discovery'};
 const future=(await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body:{...base,session_date:futureDate,title:'Future review session'}}));
 assert.equal(future.status,201,JSON.stringify(future.data));
 const traineeIds=[trainee.id];
 const early=await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{batch_id:batch.id,activity_id:'quiz-discovery',session_plan_id:future.data.record.id,due_date:futureDate,instructions:'Early review attempt',trainee_ids:traineeIds}});
 assert.equal(early.status,409,JSON.stringify(early.data));
 const current=(await request('activities/session-plans',{method:'POST',cookie:instructorCookie,body:{...base,session_date:today(),title:'Current review session'}}));
 assert.equal(current.status,201,JSON.stringify(current.data));
 const before=(await request('state',{cookie:adminCookie})).data;
 const body={batch_id:batch.id,activity_id:'quiz-discovery',session_plan_id:current.data.record.id,due_date:today(),instructions:'Spaced retrieval · discovery.',trainee_ids:traineeIds};
 const competing=await Promise.all([
  request('activities/assign',{method:'POST',cookie:instructorCookie,body}),
  request('activities/assign',{method:'POST',cookie:adminCookie,body}),
 ]);
 assert.deepEqual(competing.map(result=>result.status).sort(),[201,409]);
 const created=competing.find(result=>result.status===201);
 const assignments=(await request('activities',{cookie:adminCookie})).data.assignments;
 const assignment=assignments.find(row=>row.id===created.data.record.id);
 assert.ok(assignment);assert.equal(assignment.participants.length,1);assert.equal(assignment.participants[0].trainee_id,trainee.id);
 const plans=(await request('activities/session-plans',{cookie:adminCookie})).data.plans;
 const linked=plans.find(plan=>plan.id===current.data.record.id);
 assert.equal(linked.linked_assignment_id,assignment.id);assert.equal(linked.version,2);
 const after=(await request('state',{cookie:adminCookie})).data;
 for(const key of ['batches','trainees','assessments','daily_attendance'])assert.deepEqual(after[key],before[key],`linked quiz changed ${key}`);
 assert.ok(after.audit_log.some(row=>row.action==='link-session-quiz'&&row.entity_id===current.data.record.id));
});
test('Academy Studio learner links run a private, one-submit quiz loop and stream the real grade to trainers',async()=>{
 const library=await request('activities/library',{cookie:instructorCookie});assert.equal(library.status,200);assert.equal(library.data.activities.length,8);assert.ok(library.data.activities.every(activity=>!('questions'in activity)));
 const created=await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{batch_id:batch.id,activity_id:'quiz-discovery',instructions:'Listen for the client goal before recommending.',due_date:'2026-10-04',trainee_ids:[trainee.id]}});
 assert.equal(created.status,201,JSON.stringify(created.data));assert.equal(created.data.record.title,'Discovery Sprint');
 const assignmentId=created.data.record.id;
 assert.equal((await request('activities/links',{method:'POST',cookie:viewerCookie,body:{assignment_id:assignmentId}})).status,403);
 const issued=await request('activities/links',{method:'POST',cookie:instructorCookie,body:{assignment_id:assignmentId}});
 assert.equal(issued.status,200,JSON.stringify(issued.data));assert.equal(issued.data.links.length,1);assert.equal(issued.data.links[0].trainee_name,'API Trainee');
 const firstCode=issued.data.links[0].code;assert.match(firstCode,/^[A-Za-z0-9_-]{43}$/);assert.ok(!JSON.stringify(issued.data).includes('code_hash'));
 const rotated=await request('activities/links',{method:'POST',cookie:instructorCookie,body:{assignment_id:assignmentId}});assert.equal(rotated.status,200);
 const code=rotated.data.links[0].code;assert.notEqual(code,firstCode);assert.equal((await request('activities/learner/open',{method:'POST',body:{code:firstCode}})).status,403);
 const initial=await request('activities',{cookie:adminCookie}),initialAssignment=initial.data.assignments.find(item=>item.id===assignmentId),initialPerson=initialAssignment.participants[0];
 assert.ok(!('learner_code_hash'in initialPerson));assert.ok(!('learner_answers'in initialPerson));
 const opened=await request('activities/learner/open',{method:'POST',body:{code}});
 assert.equal(opened.status,200,JSON.stringify(opened.data));assert.equal(opened.data.started,true);assert.equal(opened.data.trainee_name,'API Trainee');
 assert.equal(opened.data.quiz.questions.length,5);assert.ok(opened.data.quiz.questions.every(question=>!('answer'in question)&&!('explanation'in question)));
 assert.equal(opened.data.draft,null);
 const draftAnswers=[{question_id:'d1',choice:1,used_hint:true},{question_id:'d2',choice:0,used_hint:false}];
 assert.equal((await request('activities/learner/draft',{method:'POST',body:{code,answers:draftAnswers,current_index:2}})).status,400);
 const savedDraft=await request('activities/learner/draft',{method:'POST',body:{code,answers:draftAnswers,current_index:2,expected_version:0,confidence:'private-only'}});
 assert.equal(savedDraft.status,200,JSON.stringify(savedDraft.data));assert.ok(savedDraft.data.saved_at);assert.equal(savedDraft.data.version,1);
 assert.equal((await request('activities/learner/draft',{method:'POST',body:{code,answers:draftAnswers,current_index:2,expected_version:0}})).status,409);
 assert.equal((await request('activities/learner/draft',{method:'POST',body:{code,answers:[{question_id:'unknown',choice:0}],current_index:0,expected_version:1}})).status,400);
 const staffDuringDraft=(await request('activities',{cookie:adminCookie})).data.assignments.find(item=>item.id===assignmentId).participants[0];
 assert.ok(!('learner_draft_answers'in staffDuringDraft));assert.ok(!('learner_answers'in staffDuringDraft));
 const resumed=await request('activities/learner/open',{method:'POST',body:{code}});
 assert.equal(resumed.status,200);assert.deepEqual(resumed.data.draft.answers,draftAnswers);assert.equal(resumed.data.draft.current_index,2);assert.equal(resumed.data.draft.version,1);
 assert.ok(resumed.data.quiz.questions.every(question=>!('answer'in question)&&!('explanation'in question)));
 const live=(await request('activities',{cookie:adminCookie})).data.assignments.find(item=>item.id===assignmentId).participants[0];
 assert.equal(live.status,'In Progress');assert.equal(live.score,null);
 assert.equal((await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:assignmentId,trainee_id:trainee.id,expected_version:live.version,status:'Completed',score:100,trainer_feedback:'manual overwrite'}})).status,409);
 const answers=[{question_id:'d1',choice:1},{question_id:'d2',choice:0},{question_id:'d3',choice:1},{question_id:'d4',choice:1},{question_id:'d5',choice:2}];
 const submitted=await request('activities/learner/submit',{method:'POST',body:{code,answers,score:100,earned_xp:500}});
 assert.equal(submitted.status,200,JSON.stringify(submitted.data));assert.equal(submitted.data.result.score,80);assert.equal(submitted.data.result.correct,4);assert.equal(submitted.data.result.xp,400);
 const shared=(await request('activities',{cookie:adminCookie})).data.assignments.find(item=>item.id===assignmentId).participants[0];
 assert.equal(shared.status,'Completed');assert.equal(shared.score,80);assert.equal(shared.correct_count,4);assert.equal(shared.earned_xp,400);assert.ok(shared.learner_submitted_at);
 assert.ok(!('learner_answers'in shared));assert.ok(!('learner_draft_answers'in shared));assert.equal(shared.learning_insight.focus[0].label,'Client qualification');assert.equal(shared.learning_insight.suggested_activity.id,'quiz-qualification');
 assert.equal((await request('activities/pulse')).status,401);assert.equal((await request('activities/pulse',{cookie:viewerCookie})).status,403);assert.equal((await request('activities/pulse?batch_id=not-a-batch',{cookie:instructorCookie})).status,400);
 const pulse=await request(`activities/pulse?batch_id=${batch.id}&company_id=${company.id}`,{cookie:instructorCookie});assert.equal(pulse.status,200,JSON.stringify(pulse.data));assert.equal(pulse.data.pulse.learner_count,1);assert.equal(pulse.data.pulse.submission_count,1);assert.ok(pulse.data.pulse.focus.some(skill=>skill.skill==='qualification'));assert.equal(pulse.data.pulse.recommended_activity.id,'quiz-qualification');assert.ok(!JSON.stringify(pulse.data).includes('API Trainee'));assert.ok(!('answers'in pulse.data.pulse));
 assert.equal((await request('activities/learner/submit',{method:'POST',body:{code,answers}})).status,409);
 assert.equal((await request('activities/learner/draft',{method:'POST',body:{code,answers:draftAnswers,current_index:2,expected_version:1}})).status,409);
 assert.equal((await request('activities/learner/open',{method:'POST',body:{code:'A'.repeat(43)}})).status,403);
 const closed=await request('activities/close',{method:'POST',cookie:instructorCookie,body:{id:assignmentId,expected_version:1,status:'Closed'}});assert.equal(closed.status,200);
 const reopened=await request('activities/learner/open',{method:'POST',body:{code}});assert.equal(reopened.status,200);assert.equal(reopened.data.completed,true);assert.equal(reopened.data.result.score,80);assert.ok(!('draft'in reopened.data));
});
test('Trainer-made challenges publish securely, run as private quizzes and live rooms, and archive without breaking history',async()=>{
 const challenge={title:'First Call Lab',category:'Discovery conversations',level:'Core',duration_minutes:6,description:'Practice curiosity before recommendation.',study_cards:[{front:'What should you learn first?',back:'The client goal, timing, and priorities—then check your understanding.'}],questions:Array.from({length:3},(_,index)=>({prompt:`A client starts with a broad request. What is your best next move in round ${index+1}?`,options:['Send all available options.','Ask a focused open question and listen.','Promise the result they hope for.','Choose their main priority for them.'],answer:1,skill:'discovery',hint:'Start with the client’s reason for asking.',explanation:'A focused open question helps surface the client’s own goal before you recommend anything.'}))};
 assert.equal((await request('activities/custom',{method:'POST',body:challenge})).status,401);
 assert.equal((await request('activities/custom',{method:'POST',cookie:viewerCookie,body:challenge})).status,403);
 assert.equal((await request('activities/custom',{method:'POST',cookie:instructorCookie,body:{...challenge,questions:challenge.questions.slice(0,2)}})).status,400);
 const created=await request('activities/custom',{method:'POST',cookie:instructorCookie,body:challenge});assert.equal(created.status,201,JSON.stringify(created.data));
 const customId=created.data.record.id;assert.match(customId,/^studio-[a-f0-9]{32}$/);assert.ok(!JSON.stringify(created.data).includes('answer'));
 const library=(await request('activities/library',{cookie:viewerCookie})).data.activities,summary=library.find(item=>item.id===customId);assert.ok(summary?.is_custom);assert.ok(!('questions'in summary));
 const facilitator=(await request('activities/facilitator-deck',{cookie:instructorCookie})).data.activities.find(item=>item.id===customId);assert.equal(facilitator.questions[0].answer,1);
 const assignmentResult=await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{batch_id:batch.id,activity_id:customId,trainee_ids:[trainee.id],instructions:'Practice a calm and curious opening.'}});assert.equal(assignmentResult.status,201,JSON.stringify(assignmentResult.data));
 const assignmentId=assignmentResult.data.record.id,links=await request('activities/links',{method:'POST',cookie:instructorCookie,body:{assignment_id:assignmentId}});assert.equal(links.status,200);const code=links.data.links[0].code;
 const learner=await request('activities/learner/open',{method:'POST',body:{code}});assert.equal(learner.status,200,JSON.stringify(learner.data));assert.equal(learner.data.quiz.questions.length,3);assert.equal(learner.data.quiz.study_cards.length,1);assert.ok(learner.data.quiz.questions.every(question=>!('answer'in question)&&!('skill'in question)));
 const live=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:{activity_id:customId,teams:['North Stars','Bright Sparks','Comet Crew'],timer_duration:0}});assert.equal(live.status,201,JSON.stringify(live.data));
 assert.equal((await request('activities/live/info',{method:'POST',body:{code:live.data.join_code}})).data.total_rounds,3);
 const archived=await request('activities/custom/archive',{method:'POST',cookie:instructorCookie,body:{id:customId}});assert.equal(archived.status,200);
 assert.ok(!(await request('activities/library',{cookie:instructorCookie})).data.activities.some(item=>item.id===customId));
 assert.equal((await request('activities/assign',{method:'POST',cookie:instructorCookie,body:{batch_id:batch.id,activity_id:customId,trainee_ids:[trainee.id]}})).status,400);
 const resumedArchivedRoom=await request('activities/live/resume',{method:'POST',cookie:instructorCookie,body:{room_id:live.data.room_id}});assert.equal(resumedArchivedRoom.status,200);assert.equal(resumedArchivedRoom.data.room.activity.questions.length,3);assert.equal(resumedArchivedRoom.data.room.activity.questions[0].answer,1);
 const answers=learner.data.quiz.questions.map(question=>({question_id:question.id,choice:1}));answers[0].choice=0;
 const submitted=await request('activities/learner/submit',{method:'POST',body:{code,answers}});assert.equal(submitted.status,200,JSON.stringify(submitted.data));assert.equal(submitted.data.result.score,67);assert.equal(submitted.data.result.results[0].skill,'discovery');
 const reopened=await request('activities/learner/open',{method:'POST',body:{code}});assert.equal(reopened.status,200);assert.equal(reopened.data.completed,true);assert.equal(reopened.data.result.score,67);
 const host=(await request('activities/live/host?room_id='+live.data.room_id,{cookie:instructorCookie}));assert.equal(host.status,200);assert.equal(host.data.teams.length,3);assert.equal(host.data.activity.title,'First Call Lab');
 const shared=(await request('activities',{cookie:adminCookie})).data.assignments.find(item=>item.id===assignmentId);assert.equal(shared.participants[0].score,67);assert.ok(shared.participants[0].learning_insight.focus.some(item=>item.label==='Client discovery'&&item.accuracy===80));
 assert.equal((await request('activities/participant',{method:'PATCH',cookie:instructorCookie,body:{assignment_id:assignmentId,trainee_id:trainee.id,expected_version:shared.participants[0].version,status:'Completed',score:100,trainer_feedback:'override'}})).status,409);
});
test('Live phone rooms sync anonymous class answers and temporary team points without changing Academy records',async()=>{
 assert.equal((await request('activities/live/create',{method:'POST',cookie:viewerCookie,body:{activity_id:'quiz-discovery',team_one:'North Stars',team_two:'Bright Sparks',timer_duration:30}})).status,403);
 const created=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:{activity_id:'quiz-discovery',team_one:'North Stars',team_two:'Bright Sparks',timer_duration:30}});
 assert.equal(created.status,201,JSON.stringify(created.data));assert.match(created.data.join_code,/^[2-9A-HJ-NP-Z]{10}$/);assert.ok(!JSON.stringify(created.data).includes('code_hash'));
 const roomId=created.data.room_id;let code=created.data.join_code;const info=await request('activities/live/info',{method:'POST',body:{code:code.toLowerCase()}});
 assert.equal(info.status,200);assert.equal(info.data.title,'Discovery Sprint');assert.deepEqual(info.data.teams.map(team=>team.name),['North Stars','Bright Sparks']);assert.ok(!JSON.stringify(info.data).includes('question'));
 const joined=await request('activities/live/join',{method:'POST',body:{code,nickname:'Orbit',team_no:1}});
 assert.equal(joined.status,200,JSON.stringify(joined.data));assert.match(joined.data.seat_token,/^[A-Za-z0-9_-]{43}$/);assert.ok(!JSON.stringify(joined.data).includes('token_hash'));
 const seat=joined.data.seat_token,initial=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});
 assert.equal(initial.status,200);assert.equal(initial.data.question.prompt.includes('two-bedroom'),true);assert.equal('answer'in initial.data.question,false);assert.equal('explanation'in initial.data.question,false);
 assert.equal((await request('activities/live/host?room_id='+roomId,{cookie:adminCookie})).status,403);
 const trainer=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});assert.equal(trainer.status,200);assert.equal(trainer.data.response_count,0);assert.equal('answer'in trainer.data.question,false);
 const correct=(await request('activities/facilitator-deck',{cookie:instructorCookie})).data.activities.find(activity=>activity.id==='quiz-discovery').questions[0].answer;
 assert.equal((await request('activities/live/answer',{method:'POST',body:{seat_token:seat,choice:9}})).status,400);
 const answered=await request('activities/live/answer',{method:'POST',body:{seat_token:seat,choice:correct}});assert.equal(answered.status,200);assert.equal(answered.data.player.choice,correct);assert.equal(answered.data.revealed,false);
 const waiting=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});assert.equal(waiting.data.response_count,1);assert.deepEqual(waiting.data.answer_counts,[0,1,0,0]);assert.deepEqual(waiting.data.responses,[]);
 assert.equal((await request('activities/live/timer',{method:'POST',cookie:viewerCookie,body:{room_id:roomId,ends_at:new Date(Date.now()+20000).toISOString()}})).status,403);
 const timed=await request('activities/live/timer',{method:'POST',cookie:instructorCookie,body:{room_id:roomId,ends_at:new Date(Date.now()+20000).toISOString()}});assert.equal(timed.status,200);assert.ok(timed.data.room.timer_ends_at);
 const revealed=await request('activities/live/reveal',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}});assert.equal(revealed.status,200);assert.equal(revealed.data.responses[0].correct,true);assert.equal(revealed.data.teams[0].points,100);
 const result=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});assert.equal(result.data.revealed,true);assert.equal(result.data.question.answer,correct);assert.ok(result.data.question.explanation);assert.equal(result.data.player.awarded_points,100);assert.equal(result.data.player.points,100);
 const advanced=await request('activities/live/advance',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}});assert.equal(advanced.status,200);assert.equal(advanced.data.room.round_index,1);assert.equal(advanced.data.room.revealed,false);
 const next=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});assert.equal(next.data.round_index,1);assert.equal(next.data.player.choice,null);assert.equal('answer'in next.data.question,false);
 assert.equal((await request('activities/live/active')).status,401);assert.equal((await request('activities/live/active',{cookie:viewerCookie})).status,403);
 const active=await request('activities/live/active',{cookie:instructorCookie});assert.equal(active.status,200);assert.ok(active.data.rooms.some(room=>room.id===roomId&&room.players===1));
 assert.equal((await request('activities/live/resume',{method:'POST',cookie:adminCookie,body:{room_id:roomId}})).status,403);
 const resumed=await request('activities/live/resume',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}});assert.equal(resumed.status,200,JSON.stringify(resumed.data));assert.notEqual(resumed.data.join_code,code);assert.equal(resumed.data.room.room.round_index,1);assert.equal(resumed.data.room.teams[0].points,100);assert.equal((await request('activities/live/info',{method:'POST',body:{code}})).status,404);code=resumed.data.join_code;
 const reconnected=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});assert.equal(reconnected.status,200);assert.equal(reconnected.data.round_index,1);assert.equal(reconnected.data.player.points,100);
 assert.equal((await request('activities/live/resume',{method:'POST',cookie:instructorCookie,body:{room_id:'00000000-0000-4000-8000-000000000000'}})).status,404);
 const before=(await request('state',{cookie:adminCookie})).data;
 assert.equal((await request('activities/live/close',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}})).status,200);
 const after=(await request('state',{cookie:adminCookie})).data;
 for(const key of ['batches','trainees','assessments','daily_attendance'])assert.deepEqual(after[key],before[key],`live room must not change ${key}`);
 assert.equal((await request('activities/live/join',{method:'POST',body:{code,nickname:'Late join',team_no:2}})).status,409);
 const closedSeat=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});assert.equal(closedSeat.data.room_closed,true);
});
test('Live quiz confidence is private before reveal and becomes only an anonymous cohort signal',async()=>{
 const before=(await request('state',{cookie:adminCookie})).data;
 const activity=(await request('activities/facilitator-deck',{cookie:instructorCookie})).data.activities.find(item=>item.id==='quiz-discovery');
 const created=await request('activities/live/create',{method:'POST',cookie:adminCookie,body:{activity_id:activity.id,teams:['North Stars','Bright Sparks'],timer_duration:0}});
 assert.equal(created.status,201,JSON.stringify(created.data));const roomId=created.data.room_id,code=created.data.join_code,correct=activity.questions[0].answer,wrong=(correct+1)%activity.questions[0].options.length,seats=[];
 for(let index=0;index<7;index++){
  const joined=await request('activities/live/join',{method:'POST',body:{code,nickname:`Reflect ${index}`,team_no:index%2+1}});
  assert.equal(joined.status,200,JSON.stringify(joined.data));seats.push(joined.data.seat_token);
 }
 assert.equal((await request('activities/live/answer',{method:'POST',body:{seat_token:seats[0],choice:correct,confidence:'certain'}})).status,400);
 const correctPattern=[false,true,false,true,true,true,true];
 for(let index=0;index<seats.length;index++){
  const confidence=index<3?'confident':index<6?'tentative':undefined;
  const body={seat_token:seats[index],choice:correctPattern[index]?correct:wrong,...(confidence?{confidence}:{})};
  const submitted=await request('activities/live/answer',{method:'POST',body});
  assert.equal(submitted.status,200,JSON.stringify(submitted.data));
  assert.equal(submitted.data.player.confidence,confidence??null);
  assert.equal('confidence_summary'in submitted.data,false);
  if(index===0){
   const ownState=await request('activities/live/state',{method:'POST',body:{seat_token:seats[0]}});
   assert.equal(ownState.data.player.confidence,'confident');
   assert.equal('confidence_summary'in ownState.data,false);
  }
 }
 const hidden=await request('activities/live/host?room_id='+roomId,{cookie:adminCookie});
 assert.equal(hidden.status,200);assert.equal(hidden.data.confidence_summary,null);assert.deepEqual(hidden.data.responses,[]);
 const revealed=await request('activities/live/reveal',{method:'POST',cookie:adminCookie,body:{room_id:roomId}});
 assert.equal(revealed.status,200);
 assert.deepEqual(revealed.data.confidence_summary,{count:6,confident:{count:3,accuracy:33},tentative:{count:3,accuracy:100}});
 assert.ok(revealed.data.responses.every(response=>!('confidence'in response)));
 assert.equal(JSON.stringify(revealed.data.responses).includes('tentative'),false);
 assert.equal((await request('activities/live/close',{method:'POST',cookie:adminCookie,body:{room_id:roomId}})).status,200);
 const after=(await request('state',{cookie:adminCookie})).data;
 for(const key of ['batches','trainees','assessments','daily_attendance'])assert.deepEqual(after[key],before[key],`live confidence changed ${key}`);
});
test('Sequence Sprint uses private ordered-step submissions and awards only temporary reveal-time points',async()=>{
 const before=(await request('state',{cookie:adminCookie})).data;
 const deck=(await request('activities/facilitator-deck',{cookie:instructorCookie})).data.activities;
 const activity=deck.find(item=>item.id==='sequence-sprint');assert.ok(activity);assert.equal(activity.questions.length,5);
 const library=(await request('activities/library',{cookie:viewerCookie})).data.activities;assert.ok(!library.some(item=>item.id==='sequence-sprint'));
 const created=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:{activity_id:activity.id,teams:['North Stars','Bright Sparks'],timer_duration:0}});
 assert.equal(created.status,201,JSON.stringify(created.data));const roomId=created.data.room_id,code=created.data.join_code;
 const joined=await request('activities/live/join',{method:'POST',body:{code,nickname:'Order Taker',team_no:1}});assert.equal(joined.status,200,JSON.stringify(joined.data));
 const seat=joined.data.seat_token,initial=await request('activities/live/state',{method:'POST',body:{seat_token:seat}}),question=initial.data.question;
 assert.equal(initial.status,200);assert.equal(question.type,'sequence');assert.equal(question.steps.length,3);assert.ok(!('options'in question));assert.ok(!('answer'in question));assert.ok(!('explanation'in question));
 const initialHost=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});assert.equal(initialHost.status,200);assert.equal(initialHost.data.question.type,'sequence');assert.ok(!('answer'in initialHost.data.question));assert.equal(initialHost.data.answer_counts,null);
 const answer=activity.questions[0].answer;
 assert.equal((await request('activities/live/answer',{method:'POST',body:{seat_token:seat,choice:6}})).status,400);
 const submitted=await request('activities/live/answer',{method:'POST',body:{seat_token:seat,choice:answer}});assert.equal(submitted.status,200);assert.equal(submitted.data.player.choice,answer);assert.equal(submitted.data.player.correct,null);assert.equal(submitted.data.player.awarded_points,0);assert.equal('answer'in submitted.data.question,false);
 const hostWaiting=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});assert.equal(hostWaiting.data.response_count,1);assert.equal(hostWaiting.data.answer_counts,null);assert.deepEqual(hostWaiting.data.responses,[]);
 const revealed=await request('activities/live/reveal',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}});assert.equal(revealed.status,200);assert.equal(revealed.data.responses[0].correct,true);assert.equal(revealed.data.teams[0].points,100);assert.equal(revealed.data.question.answer,answer);
 const phoneReveal=await request('activities/live/state',{method:'POST',body:{seat_token:seat}});assert.equal(phoneReveal.data.revealed,true);assert.equal(phoneReveal.data.player.correct,true);assert.equal(phoneReveal.data.player.awarded_points,100);assert.equal(phoneReveal.data.question.answer,answer);assert.ok(phoneReveal.data.question.explanation);
 assert.equal((await request('activities/live/close',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}})).status,200);
 const after=(await request('state',{cookie:adminCookie})).data;
 for(const key of ['batches','trainees','assessments','daily_attendance'])assert.deepEqual(after[key],before[key],`Sequence Sprint must not change ${key}`);
});
test('Live rooms support two to four named teams and reject seats outside each room',async()=>{
 for(const teams of [['North Stars','Bright Sparks'],['North Stars','Bright Sparks','Comet Crew'],['North Stars','Bright Sparks','Comet Crew','Green Meteors']]){
  const created=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:{activity_id:'quiz-discovery',teams,timer_duration:0}});
  assert.equal(created.status,201,JSON.stringify(created.data));
  const roomId=created.data.room_id,code=created.data.join_code;
  const info=await request('activities/live/info',{method:'POST',body:{code}});
  assert.equal(info.status,200);assert.deepEqual(info.data.teams.map(team=>team.name),teams);
  const selectedTeam=teams.length,joined=await request('activities/live/join',{method:'POST',body:{code,nickname:`Team ${teams.length}`,team_no:selectedTeam}});
  assert.equal(joined.status,200,JSON.stringify(joined.data));assert.equal(joined.data.room.team.name,teams.at(-1));
  assert.equal(joined.data.room.team_scores.length,teams.length);
  assert.equal((await request('activities/live/join',{method:'POST',body:{code,nickname:`Extra ${teams.length}`,team_no:teams.length+1}})).status,400);
  const host=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});assert.equal(host.status,200);assert.deepEqual(host.data.teams.map(team=>team.name),teams);
  assert.equal((await request('activities/live/close',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}})).status,200);
 }
 const duplicate=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:{activity_id:'quiz-discovery',teams:['Same','same'],timer_duration:0}});
 assert.equal(duplicate.status,400);
});
test('Session-run class pulses are anonymous, ungraded, privacy-thresholded, and isolated from Academy records',async()=>{
 const pulse={mode:'pulse',title:'Discovery confidence',prompt:'How ready do you feel to explain the client discovery sequence?',options:['Ready to explain it','I want another example','I want to practise it'],timer_duration:30};
 assert.equal((await request('activities/live/create',{method:'POST',cookie:viewerCookie,body:pulse})).status,403);
 for(const invalid of [{...pulse,options:['Same','same']},{...pulse,prompt:'tiny'},{...pulse,timer_duration:60},{...pulse,mode:'unsupported'}])assert.equal((await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:invalid})).status,400);
 const before=(await request('state',{cookie:adminCookie})).data;
 const created=await request('activities/live/create',{method:'POST',cookie:instructorCookie,body:pulse});assert.equal(created.status,201,JSON.stringify(created.data));
 const roomId=created.data.room_id,code=created.data.join_code,info=await request('activities/live/info',{method:'POST',body:{code}});
 assert.equal(info.status,200);assert.equal(info.data.mode,'pulse');assert.equal(info.data.total_rounds,1);assert.deepEqual(info.data.teams.map(team=>team.name),['Whole class']);
 const seats=[];
 for(let index=0;index<3;index++){
  const joined=await request('activities/live/join',{method:'POST',body:{code,nickname:`Identity ${index}`,team_no:4}});
  assert.equal(joined.status,200,JSON.stringify(joined.data));assert.equal(joined.data.room.mode,'pulse');
  assert.equal('nickname'in joined.data.room.player,false);assert.equal('points'in joined.data.room.player,false);assert.equal('team'in joined.data.room,false);assert.equal('answer'in joined.data.room.question,false);seats.push(joined.data.seat_token);
 }
 const hostBefore=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});
 assert.equal(hostBefore.status,200);assert.equal(hostBefore.data.room.mode,'pulse');assert.equal(hostBefore.data.answer_counts,null);assert.deepEqual(hostBefore.data.responses,[]);assert.deepEqual(hostBefore.data.teams[0].players,[]);
 const choices=[2,2,0];
 for(let index=0;index<seats.length;index++){
  if(index===0)assert.equal((await request('activities/live/answer',{method:'POST',body:{seat_token:seats[index],choice:choices[index],confidence:'confident'}})).status,400);
  const answered=await request('activities/live/answer',{method:'POST',body:{seat_token:seats[index],choice:choices[index]}});
  assert.equal(answered.status,200);assert.equal(answered.data.player.choice,choices[index]);assert.equal(answered.data.answer_counts,null);assert.equal('correct'in answered.data.player,false);
 }
 const hostWithCounts=await request('activities/live/host?room_id='+roomId,{cookie:instructorCookie});
 assert.deepEqual(hostWithCounts.data.answer_counts,[1,0,2]);assert.deepEqual(hostWithCounts.data.responses,[]);assert.equal(JSON.stringify(hostWithCounts.data).includes('Pulse-'),false);
 const phoneBeforeReveal=await request('activities/live/state',{method:'POST',body:{seat_token:seats[0]}});assert.equal(phoneBeforeReveal.data.answer_counts,null);assert.equal(phoneBeforeReveal.data.revealed,false);
 assert.equal((await request('activities/live/reveal',{method:'POST',cookie:viewerCookie,body:{room_id:roomId}})).status,403);
 const revealed=await request('activities/live/reveal',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}});
 assert.equal(revealed.status,200);assert.equal(revealed.data.room.revealed,true);assert.equal(revealed.data.room.correct_choice,null);assert.equal(revealed.data.teams[0].points,0);assert.deepEqual(revealed.data.teams[0].players,[]);assert.deepEqual(revealed.data.responses,[]);
 const learnerResult=await request('activities/live/state',{method:'POST',body:{seat_token:seats[0]}});
 assert.deepEqual(learnerResult.data.answer_counts,[1,0,2]);assert.equal('answer'in learnerResult.data.question,false);assert.equal('explanation'in learnerResult.data.question,false);assert.equal('nickname'in learnerResult.data.player,false);
 assert.equal((await request('activities/live/answer',{method:'POST',body:{seat_token:seats[0],choice:1}})).status,409);
 assert.equal((await request('activities/live/close',{method:'POST',cookie:instructorCookie,body:{room_id:roomId}})).status,200);
 assert.equal((await request('activities/live/state',{method:'POST',body:{seat_token:seats[0]}})).data.room_closed,true);
 const after=(await request('state',{cookie:adminCookie})).data;
 for(const key of ['batches','trainees','assessments','daily_attendance'])assert.deepEqual(after[key],before[key],`pulse must not change ${key}`);
});
test('API state excludes password hashes and session tokens',async()=>{const r=await request('state',{cookie:adminCookie});assert.ok(!JSON.stringify(r.data).includes('password_hash'));assert.ok(!('users'in r.data));assert.ok(!('sessions'in r.data));assert.equal(r.response.headers.get('cache-control'),'no-store');});
test('Score validation rejects tampered out-of-range requests',async()=>{const data={trainee_id:trainee.id,batch_id:batch.id,assessment_title:'Final',mapping:99,product_knowledge:5,presentability:5,soft_skills:5,assessment_outcome:'Aced',instructor_comment:'',report:'',report_kind:'template'};assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'assessments',action:'create',data}})).status,400);});
test('Bulk attendance is all-or-nothing on duplicate daily entries',async()=>{const data={trainee_id:trainee.id,batch_id:batch.id,date:batch.start_date,arrival_time:null,departure_time:null,status:'Absent',is_late:false};const r=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'daily_attendance',records:[{action:'create',data},{action:'create',data}]}});assert.equal(r.status,409);const state=(await request('state',{cookie:adminCookie})).data;assert.equal(state.daily_attendance.filter(r=>r.trainee_id===trainee.id).length,0);});
test('Assessment day saves with present attendance and trainee can be marked stopped',async()=>{let response=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'daily_attendance',action:'create',data:{trainee_id:trainee.id,batch_id:batch.id,date:batch.session_dates[1],arrival_time:null,departure_time:null,status:'Present',assessment_day:true,is_late:false}}});assert.equal(response.status,200);assert.equal(response.data.records[0].assessment_day,true);assert.equal(response.data.records[0].status,'Present');let updated=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'update',id:trainee.id,expectedVersion:1,data:{...trainee,enrollment_status:'Stopped Attending'}}});assert.equal(updated.status,200);assert.equal(updated.data.records[0].enrollment_status,'Stopped Attending');updated=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'update',id:trainee.id,expectedVersion:2,data:{...updated.data.records[0],enrollment_status:'Active'}}});assert.equal(updated.status,200);});
test('Stale expectedVersion returns conflict without overwriting',async()=>{const body={table:'companies',action:'update',id:company.id,expectedVersion:1,data:{name:'API Renamed Company'}};assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body})).status,200);assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body})).status,409);});
test('AI without provider configuration returns 503, not a fabricated AI report',async()=>assert.equal((await request('ai',{method:'POST',cookie:adminCookie,body:{traineeId:trainee.id,kind:'attendance',consent:true}})).status,503));
test('Unknown tables and endpoints are rejected',async()=>{assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'users',action:'create',data:{role:'admin'}}})).status,400);assert.equal((await request('no-such-route',{cookie:adminCookie})).status,404);});
test('Live event stream emits a change notification after a successful mutation',async()=>{const controller=new AbortController();const response=await handleApi(new Request(process.env.APP_URL+'/api/events',{headers:{cookie:adminCookie},signal:controller.signal}));assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/event-stream/);const reader=response.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/connected/);await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'companies',action:'create',data:{name:'SSE Company'}}});const next=await reader.read();assert.match(new TextDecoder().decode(next.value),/refresh/);controller.abort();await reader.cancel();});
test('Logout invalidates the session and expires its cookie',async()=>{const login=await request('auth/login',{method:'POST',body:{email:'instructor@example.test',password:'API-Test-Password-123!'}});const r=await request('auth/logout',{method:'POST',cookie:login.cookie});assert.match(r.response.headers.getSetCookie()[0],/Max-Age=0/);assert.equal((await request('state',{cookie:login.cookie})).status,401);});
