import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {id,sessionDates} from '../public/modules/core.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'red-academy-api-'));
process.env.DATABASE_MODE='sqlite';process.env.DATABASE_PATH=path.join(dir,'api.db');process.env.SEED_SAMPLE_DATA='false';
process.env.BOOTSTRAP_ADMIN_EMAIL='admin@example.test';process.env.BOOTSTRAP_ADMIN_PASSWORD='API-Test-Password-123!';
process.env.APP_URL='http://localhost:3000';delete process.env.APP_ENV;delete process.env.OPENAI_API_KEY;delete process.env.OPENAI_MODEL;
const {handleApi,repository}=await import('../server/service.mjs');
let adminCookie='',viewerCookie='',instructorCookie='',company,batch,trainee;
async function request(route,{method='GET',body,cookie='',origin=process.env.APP_URL,custom=true,raw}={}){
 const headers=new Headers();if(cookie)headers.set('cookie',cookie);if(method!=='GET'){headers.set('content-type','application/json');if(origin)headers.set('origin',origin);if(custom)headers.set('x-red-request','1');}
 const response=await handleApi(new Request(process.env.APP_URL+'/api/'+route,{method,headers,...(method!=='GET'?{body:raw??JSON.stringify(body||{})}:{})}));
 const data=response.headers.get('content-type')?.includes('application/json')?await response.json():null;
 return {response,data,status:response.status,cookie:response.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};
}
before(async()=>{const repo=await repository();await repo.setup({token:repo.setupToken,email:'admin@example.test',full_name:'Test Administrator',password:process.env.BOOTSTRAP_ADMIN_PASSWORD});const login=await request('auth/login',{method:'POST',body:{email:'admin@example.test',password:process.env.BOOTSTRAP_ADMIN_PASSWORD}});assert.equal(login.status,200);adminCookie=login.cookie;assert.equal((await request('state',{cookie:adminCookie})).data.companies.length,0);company=(await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'companies',action:'create',data:{name:'API Company'}}})).data.records[0];
 for(const role of ['viewer','instructor']){
  const invite=await request('invitations',{method:'POST',cookie:adminCookie,body:{email:role+'@example.test',full_name:role,role}});assert.equal(invite.status,201);assert.equal((await request('auth/accept-invitation',{method:'POST',body:{token:invite.data.token,password:'API-Test-Password-123!',role:'admin'}})).status,201);
  const list=await request('users',{cookie:adminCookie});const user=list.data.find(u=>u.email===role+'@example.test');
  assert.equal((await request('users',{method:'PATCH',cookie:adminCookie,body:{id:user.id,role,active:true}})).status,200);
  const login=await request('auth/login',{method:'POST',body:{email:user.email,password:'API-Test-Password-123!'}});
  if(role==='viewer')viewerCookie=login.cookie;else instructorCookie=login.cookie;
 }
 const b=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'batches',action:'create',data:{batch_name:'API Batch',status:'Active',start_date:'2026-09-06',end_date:'2026-09-19',session_dates:sessionDates('2026-09-06'),capacity:20,description:''}}});assert.equal(b.status,200);batch=b.data.records[0];
 const t=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'create',data:{trainee_name:'API Trainee',company_id:company.id,batch_id:batch.id,email:'',phone:'',job_title:'',notes:''}}});assert.equal(t.status,200);assert.equal(t.data.records.length,2);trainee=t.data.records[0];assert.equal(trainee.enrollment_status,'Active');
});
after(async()=>{(await repository()).close();fs.rmSync(dir,{recursive:true,force:true});});
test('Unauthenticated session is public; private data returns 401',async()=>{assert.equal((await request('session')).data.user,null);assert.equal((await request('state')).status,401);});
test('Session cookie is opaque, HttpOnly and SameSite=Lax',async()=>{const r=await request('auth/login',{method:'POST',body:{email:'admin@example.test',password:process.env.BOOTSTRAP_ADMIN_PASSWORD}});const cookie=r.response.headers.getSetCookie()[0];assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Lax/);assert.ok(!cookie.includes('admin@example'));});
test('Wrong Origin and missing custom header are blocked',async()=>{assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,origin:'https://evil.example',body:{}})).status,403);assert.equal((await request('auth/login',{method:'POST',custom:false,body:{}})).status,403);});
test('Malformed and non-object JSON bodies return 400, not a server crash',async()=>{for(const raw of ['{bad','null','[]','4'])assert.equal((await request('auth/login',{method:'POST',raw})).status,400);});
test('Public registration is disabled and cannot create accounts',async()=>{const email='pending@example.test';assert.equal((await request('auth/register',{method:'POST',body:{email,password:'API-Test-Password-123!',full_name:'Pending',role:'admin',active:true}})).status,403);assert.equal((await request('auth/login',{method:'POST',body:{email,password:'API-Test-Password-123!'}})).status,401);});
test('Viewer reads but cannot write or administer accounts',async()=>{assert.equal((await request('state',{cookie:viewerCookie})).status,200);assert.equal((await request('mutate',{method:'POST',cookie:viewerCookie,body:{table:'companies',action:'create',data:{name:'Forbidden'}}})).status,403);assert.equal((await request('users',{cookie:viewerCookie})).status,403);assert.equal((await request('users',{method:'PATCH',cookie:viewerCookie,body:{id:trainee.id,role:'admin',active:true}})).status,403);});
test('Instructor can create records but cannot delete company records',async()=>{const r=await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'companies',action:'create',data:{name:'Instructor Company'}}});assert.equal(r.status,200);assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'companies',action:'delete',id:r.data.records[0].id,expectedVersion:1}})).status,403);});
test('Instructor can delete operational batches and trainees',async()=>{
 const batchResponse=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'batches',action:'create',data:{batch_name:'Instructor Delete Batch',status:'Planning',start_date:'2026-10-01',end_date:'2026-10-14',session_dates:sessionDates('2026-10-01'),capacity:10,description:''}}});assert.equal(batchResponse.status,200,JSON.stringify(batchResponse.data));const newBatch=batchResponse.data.records[0];
 const traineeResponse=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'create',data:{trainee_name:'Instructor Delete Trainee',company_id:company.id,batch_id:newBatch.id,email:'',phone:'',job_title:'',notes:''}}});assert.equal(traineeResponse.status,200,JSON.stringify(traineeResponse.data));const newTrainee=traineeResponse.data.records[0];
 assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'trainees',action:'delete',id:newTrainee.id,expectedVersion:newTrainee.version}})).status,200);
 assert.equal((await request('mutate',{method:'POST',cookie:instructorCookie,body:{table:'batches',action:'delete',id:newBatch.id,expectedVersion:newBatch.version}})).status,200);
});
test('API state excludes password hashes and session tokens',async()=>{const r=await request('state',{cookie:adminCookie});assert.ok(!JSON.stringify(r.data).includes('password_hash'));assert.ok(!('users'in r.data));assert.ok(!('sessions'in r.data));assert.equal(r.response.headers.get('cache-control'),'no-store');});
test('Score validation rejects tampered out-of-range requests',async()=>{const data={trainee_id:trainee.id,batch_id:batch.id,assessment_title:'Final',mapping:99,product_knowledge:5,presentability:5,soft_skills:5,assessment_outcome:'Aced',instructor_comment:'',report:'',report_kind:'template'};assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'assessments',action:'create',data}})).status,400);});
test('Bulk attendance is all-or-nothing on duplicate daily entries',async()=>{const data={trainee_id:trainee.id,batch_id:batch.id,date:batch.start_date,arrival_time:null,departure_time:null,status:'Absent',is_late:false};const r=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'daily_attendance',records:[{action:'create',data},{action:'create',data}]}});assert.equal(r.status,409);const state=(await request('state',{cookie:adminCookie})).data;assert.equal(state.daily_attendance.filter(r=>r.trainee_id===trainee.id).length,0);});
test('Assessment day saves with present attendance and trainee can be marked stopped',async()=>{let response=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'daily_attendance',action:'create',data:{trainee_id:trainee.id,batch_id:batch.id,date:batch.session_dates[1],arrival_time:null,departure_time:null,status:'Present',assessment_day:true,is_late:false}}});assert.equal(response.status,200);assert.equal(response.data.records[0].assessment_day,true);assert.equal(response.data.records[0].status,'Present');let updated=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'update',id:trainee.id,expectedVersion:1,data:{...trainee,enrollment_status:'Stopped Attending'}}});assert.equal(updated.status,200);assert.equal(updated.data.records[0].enrollment_status,'Stopped Attending');updated=await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'trainees',action:'update',id:trainee.id,expectedVersion:2,data:{...updated.data.records[0],enrollment_status:'Active'}}});assert.equal(updated.status,200);});
test('Stale expectedVersion returns conflict without overwriting',async()=>{const body={table:'companies',action:'update',id:company.id,expectedVersion:1,data:{name:'API Renamed Company'}};assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body})).status,200);assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body})).status,409);});
test('AI without provider configuration returns 503, not a fabricated AI report',async()=>assert.equal((await request('ai',{method:'POST',cookie:adminCookie,body:{traineeId:trainee.id,kind:'attendance',consent:true}})).status,503));
test('Unknown tables and endpoints are rejected',async()=>{assert.equal((await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'users',action:'create',data:{role:'admin'}}})).status,400);assert.equal((await request('no-such-route',{cookie:adminCookie})).status,404);});
test('Live event stream emits a change notification after a successful mutation',async()=>{const controller=new AbortController();const response=await handleApi(new Request(process.env.APP_URL+'/api/events',{headers:{cookie:adminCookie},signal:controller.signal}));assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/event-stream/);const reader=response.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/connected/);await request('mutate',{method:'POST',cookie:adminCookie,body:{table:'companies',action:'create',data:{name:'SSE Company'}}});const next=await reader.read();assert.match(new TextDecoder().decode(next.value),/refresh/);controller.abort();await reader.cancel();});
test('Logout invalidates the session and expires its cookie',async()=>{const login=await request('auth/login',{method:'POST',body:{email:'instructor@example.test',password:'API-Test-Password-123!'}});const r=await request('auth/logout',{method:'POST',cookie:login.cookie});assert.match(r.response.headers.getSetCookie()[0],/Max-Age=0/);assert.equal((await request('state',{cookie:login.cookie})).status,401);});
