import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {SQLiteRepository} from '../server/sqlite.mjs';
import {prepareOperations} from '../server/service.mjs';
import {validate} from '../server/validation.mjs';
import {scores,assessedRows,averageScore,attendanceStats,batchStats,storedChecklistFor,assessmentFor,atCairo,reportFor} from '../public/modules/core.mjs';
import {scoped,attendance} from '../public/modules/views.mjs';
import {workbookData,makeXlsx,currentCsv} from '../public/modules/export.mjs';
import {actor} from './fixtures.mjs';
const seed=new URL('../data/red-academy.db',import.meta.url);
async function isolated(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'red-import-test-'));const file=path.join(dir,'test.db');fs.copyFileSync(seed,file);const access=new DatabaseSync(file);access.exec('DELETE FROM sessions; DELETE FROM invitations; DELETE FROM setup_grants; DELETE FROM users;');access.close();const repo=new SQLiteRepository(file);try{await fn(repo,await repo.state(actor));}finally{repo.db.close();fs.rmSync(dir,{recursive:true,force:true});}}
const batch=(s,n)=>s.batches.find(b=>b.batch_name==='Batch '+n);
const update=(table,r,data)=>({table,action:'update',id:r.id,expectedVersion:r.version,data:{...r,...data}});
async function save(repo,s,table,r,data){return repo.commit(prepareOperations(update(table,r,data),s,actor),actor);}

test('Imported snapshot contains 42 real batches and no configured accounts',()=>isolated(async(repo,s)=>{assert.equal(s.batches.length,42);assert.equal(s.trainees.length,903);assert.equal(s.assessments.length,847);assert.equal(s.daily_attendance.length,2606);assert.equal(repo.db.prepare('SELECT count(*) n FROM users').get().n,0);}));
test('Missing skill has unknown total while the supplied skill group remains calculable',()=>isolated(async(_,s)=>{const r=s.assessments.find(r=>r.product_knowledge===null&&r.mapping!==null);assert.equal(scores(r).tech,null);assert.equal(scores(r).overall,null);assert.notEqual(scores(r).soft,null);assert.ok(!assessedRows(s.assessments).some(a=>a.id===r.id));}));
test('Assessment filters include shared and unassigned records without a trainee join',()=>isolated(async(_,s)=>{const b=batch(s,41),d=scoped({store:{data:s},batchId:b.id,companyId:''});assert.equal(d.assessments.length,20);assert.ok(d.assessments.some(a=>a.source_meta.assessment_state==='shared'));}));
test('Attendance filter retains the unassigned Batch 42 timestamp entry',()=>isolated(async(_,s)=>{const d=scoped({store:{data:s},batchId:batch(s,42).id,companyId:''});assert.equal(d.daily_attendance.length,1);assert.equal(d.daily_attendance[0].trainee_id,null);assert.equal(d.daily_attendance[0].status,null);assert.equal(attendanceStats(d.daily_attendance).absent,0);}));
test('New absence in an undated imported batch does not invent a timestamp or a ten-day schedule',()=>isolated(async(repo,s)=>{const b=batch(s,1),t=s.trainees.find(t=>t.batch_id===b.id),date='2026-09-17';assert.equal(b.start_date,null);const body={table:'daily_attendance',action:'create',data:{trainee_id:t.id,batch_id:b.id,date,status:'Absent',arrival_time:null,departure_time:null,is_late:false}};const ops=prepareOperations(body,s,actor);assert.equal(ops[0].table,'batches');await repo.commit(ops,actor);const next=await repo.state(actor);const day=next.daily_attendance.find(d=>d.trainee_id===t.id&&d.date===date);assert.equal(day.arrival_time,null);assert.equal(batch(next,1).start_date,null);assert.deepEqual(batch(next,1).session_dates,[date]);}));
test('Historical note edits preserve original timestamp conflicts and source metadata',()=>isolated(async(repo,s)=>{const r=s.daily_attendance.find(r=>r.source_meta.flags.length);await save(repo,s,'daily_attendance',r,{absence_reason:'Reviewed without guessing a time.'});const next=(await repo.state(actor)).daily_attendance.find(d=>d.id===r.id);assert.equal(next.arrival_time,r.arrival_time);assert.equal(next.departure_time,r.departure_time);assert.deepEqual(next.source_meta,r.source_meta);assert.equal(next.version,r.version+1);}));
test('Partial assessment edit preserves NULL and creates a prior snapshot',()=>isolated(async(repo,s)=>{const r=s.assessments.find(a=>a.mapping===null);await save(repo,s,'assessments',r,{instructor_comment:'The missing skills were not recorded.'});const next=await repo.state(actor);assert.equal(next.assessments.find(a=>a.id===r.id).mapping,null);assert.equal(next.assessment_history.find(h=>h.assessment_id===r.id).snapshot.mapping,null);}));
test('Unassigned historical assessment can be saved and revised without a fake trainee ID',()=>isolated(async(repo,s)=>{const r=s.assessments.find(a=>!a.trainee_id&&a.source_meta.assessment_state!=='shared');await save(repo,s,'assessments',r,{instructor_comment:r.instructor_comment});const next=await repo.state(actor);assert.equal(next.assessments.find(a=>a.id===r.id).trainee_id,null);assert.equal(next.assessment_history.find(h=>h.assessment_id===r.id).trainee_id,null);}));
test('Shared historical assessment remains excluded after editing',()=>isolated(async(repo,s)=>{const r=s.assessments.find(a=>a.source_meta.assessment_state==='shared');await save(repo,s,'assessments',r,{instructor_comment:'Shared original retained.'});const next=(await repo.state(actor)).assessments.find(a=>a.id===r.id);assert.equal(next.trainee_id,null);assert.equal(next.analytics_included,false);}));
test('Historical NULL enrollment links cannot be forged into an arbitrary identity',()=>isolated(async(_,s)=>{const r=s.assessments.find(a=>a.source_meta.assessment_state==='shared'),t=s.trainees.find(t=>t.batch_id===r.batch_id);assert.throws(()=>prepareOperations(update('assessments',r,{trainee_id:t.id}),s,actor),/cannot be reassigned/);}));
test('Existing known historical enrollment cannot be erased through a null update',()=>isolated(async(_,s)=>{const r=s.assessments.find(a=>a.trainee_id);assert.throws(()=>prepareOperations(update('assessments',r,{trainee_id:null}),s,actor),/cannot be reassigned/);}));
test('Origin metadata cannot be overwritten from an API payload',()=>isolated(async(repo,s)=>{const r=s.trainees[0];await save(repo,s,'trainees',r,{source_id:'forged',source_meta:{origin:'forged'},notes:'A safe contact note.'});const next=(await repo.state(actor)).trainees.find(t=>t.id===r.id);assert.equal(next.source_id,r.source_id);assert.deepEqual(next.source_meta,r.source_meta);}));
test('Undated imported batch can be saved with NULL status, range and capacity',()=>isolated(async(repo,s)=>{const r=s.batches.find(b=>b.start_date===null);await save(repo,s,'batches',r,{description:'Dates not collected.',status:null});const next=(await repo.state(actor)).batches.find(b=>b.id===r.id);assert.equal(next.status,null);assert.equal(next.start_date,null);assert.equal(next.capacity,null);}));
test('Multiple imported checklist periods remain preserved as source history',()=>isolated(async(_,s)=>{const b=batch(s,30),rows=s.attendance_10day.filter(r=>r.batch_id===b.id);assert.equal(rows.length,26);for(const t of s.trainees.filter(t=>t.batch_id===b.id)){const mine=rows.filter(r=>r.trainee_id===t.id);assert.equal(mine.length,2);assert.equal(storedChecklistFor(s,t.id).period_end,'2026-02-11');}assert.equal(batchStats(s,b.id).present,0);}));
test('Batch totals count attendance directly, not once for every overlapping checklist period',()=>isolated(async(_,s)=>{const b=batch(s,31),r=s.attendance_10day.find(r=>r.batch_id===b.id),before=batchStats(s,b.id).present;s.attendance_10day.push({...r,id:crypto.randomUUID()});assert.equal(batchStats(s,b.id).present,before);}));
test('Original source content remains unchanged after an operational edit',()=>isolated(async(repo,s)=>{const r=s.assessments[0],before=await repo.sourceRecord(r.source_id);await save(repo,s,'assessments',r,{instructor_comment:'A new operational comment.'});assert.deepEqual(await repo.sourceRecord(r.source_id),before);}));
test('Source archive filter is parameterized and paginated',()=>isolated(async(repo)=>{const rows=await repo.sourceList({kind:'assessments',page:2});assert.equal(rows.total,897);assert.equal(rows.rows.length,25);assert.equal((await repo.sourceList({q:"' OR 1=1 --"})).total,0);}));
test('A source review acknowledgement does not rewrite the source or operational record',()=>isolated(async(repo,s)=>{const r=s.import_reviews.find(r=>r.status==='open'),before=await repo.sourceRecord(r.source_ids[0]);await repo.acknowledgeReview(r.id,'Retained as recorded.',actor);const after=await repo.state(actor);assert.equal(after.import_reviews.find(a=>a.id===r.id).status,'acknowledged');assert.deepEqual(await repo.sourceRecord(r.source_ids[0]),before);}));
test('Source review endpoint refuses instructor acknowledgements',()=>isolated(async(repo,s)=>{await assert.rejects(repo.acknowledgeReview(s.import_reviews[0].id,'No',{...actor,role:'instructor'}),e=>e.status===403);}));
test('Deleting a batch cascades unassigned attendance instead of leaving a batch orphan',()=>isolated(async(repo,s)=>{const b=batch(s,42),sourceCount=repo.db.prepare('SELECT count(*) n FROM source_records').get().n;await repo.commit(prepareOperations({table:'batches',action:'delete',id:b.id,expectedVersion:b.version},s,actor),actor);assert.equal(repo.db.prepare('SELECT count(*) n FROM daily_attendance WHERE batch_id=?').get(b.id).n,0);assert.equal(repo.db.prepare('SELECT count(*) n FROM source_records').get().n,sourceCount);assert.deepEqual(repo.db.prepare('PRAGMA foreign_key_check').all(),[]);}));
test('Deleting a batch with a shared assessment preserves its unassigned history snapshot',()=>isolated(async(repo,s)=>{const b=batch(s,41),shared=s.assessments.find(r=>r.source_meta.assessment_state==='shared');await repo.commit(prepareOperations({table:'batches',action:'delete',id:b.id,expectedVersion:b.version},s,actor),actor);assert.equal(repo.db.prepare('SELECT count(*) n FROM assessments WHERE batch_id=?').get(b.id).n,0);const history=repo.db.prepare('SELECT * FROM assessment_history WHERE assessment_id=?').get(shared.id);assert.equal(history.trainee_id,null);}));
test('Workbook exports live session checklists while preserving every source checklist record',()=>isolated(async(_,s)=>{const ctx={store:{data:s},batchId:'',companyId:'',route:'register'},sheets=workbookData(ctx);assert.equal(sheets.length,8);assert.equal(sheets.find(s=>s.name==='Assessments').rows.length,848);assert.equal(sheets.find(s=>s.name==='Daily attendance').rows.length,2607);assert.equal(sheets.find(s=>s.name==='10-day checklists').rows.length,265);assert.ok(sheets.find(s=>s.name==='Session checklist').rows.length>1);assert.ok(sheets.find(s=>s.name==='Assessments').rows[0].includes('Reported absence'));assert.equal(currentCsv(ctx).rows.length,2607);}));
test('Incomplete Excel percentage formulas have blank cached values, not 0%',()=>isolated(async(_,s)=>{const sheets=workbookData({store:{data:s},batchId:'',companyId:''}),sheet=sheets.find(s=>s.name==='Assessments'),r=sheet.rows.find((r,i)=>i&&r[4]===null&&r[3]!==null);assert.equal(r[8].value,null);assert.equal(r[10].value,null);assert.ok(r[8].formula.includes('COUNT('));const bytes=await makeXlsx([{...sheet,rows:[sheet.rows[0],r]}]).arrayBuffer();const text=new TextDecoder().decode(bytes);assert.match(text,/t="str"><f>IF\(COUNT/);assert.match(text,/<v><\/v>/);}));
test('Averaged outcomes exclude all incomplete/shared/not-assessed records',()=>isolated(async(_,s)=>{const all=assessedRows(s.assessments);assert.ok(all.length<s.assessments.length);assert.ok(all.every(a=>a.trainee_id&&a.mapping!==null));assert.equal(averageScore(s.assessments),all.reduce((n,r)=>n+scores(r).overall,0)/all.length);}));

test('A saved not-assessed source does not become a fabricated failing report',()=>isolated(async(_,s)=>{const r=s.assessments.find(a=>a.trainee_id&&a.source_meta.assessment_state==='not_assessed'&&!s.assessments.some(b=>b.trainee_id===a.trainee_id&&b.analytics_included));assert.ok(r);assert.match(reportFor(s,r.trainee_id),/not assessed/);assert.match(reportFor(s,r.trainee_id),/No grade has been inferred/);}));
