"""Isolated Chromium acceptance for the standalone Trainer Activities Studio.

Uses a temporary SQLite database and a local RED server. It never connects to
the configured company workspace or changes its operational data.
Requires the repository's optional Python Playwright + Chromium test setup.
"""
from pathlib import Path
import argparse, json, os, re, socket, subprocess, tempfile, time, urllib.request
from playwright.sync_api import sync_playwright, expect
import browser_harness as h

ROOT=Path(__file__).resolve().parents[1]
TODAY=subprocess.check_output(['node','--input-type=module','-e',"import {today} from './public/modules/core.mjs'; console.log(today())"],cwd=ROOT,text=True).strip()
parser=argparse.ArgumentParser()
parser.add_argument('--screenshots')
args=parser.parse_args()

def check(name,condition=True):
    if not condition: raise AssertionError(name)
    print('PASS:',name,flush=True)

def screenshot(name,page,full_page=True):
    if args.screenshots:
        directory=Path(args.screenshots);directory.mkdir(parents=True,exist_ok=True)
        page.screenshot(path=str(directory/(name+'.png')),full_page=full_page)

with tempfile.TemporaryDirectory(prefix='red-activities-studio-') as temporary:
    with socket.socket() as sock:
        sock.bind(('127.0.0.1',0));port=sock.getsockname()[1]
    h.BASE=f'http://127.0.0.1:{port}'
    env={**os.environ,'PORT':str(port),'HOST':'127.0.0.1','APP_URL':h.BASE,
         'DATABASE_PATH':str(Path(temporary)/'activities-qa.db'),'APP_ENV':'test','DATABASE_MODE':'sqlite',
         'AI_REPORTS_ENABLED':'true','GEMINI_API_KEY':'browser-test-only-not-a-real-credential',
         'BOOTSTRAP_ADMIN_EMAIL':'studio-admin@example.test','BOOTSTRAP_ADMIN_PASSWORD':'Studio-QA-Password-123!'}
    log_path=Path(temporary)/'server.log'
    with log_path.open('w') as log:
        server=subprocess.Popen(['node','server.mjs'],cwd=ROOT,env=env,stdout=log,stderr=log)
    try:
        for _ in range(100):
            try:
                urllib.request.urlopen(h.BASE+'/api/session',timeout=1).close();break
            except Exception:
                if server.poll() is not None: raise RuntimeError(log_path.read_text())
                time.sleep(.1)
        setup=re.search(r'Setup code: ([A-Za-z0-9_-]{43})',log_path.read_text())
        if not setup: raise RuntimeError('Isolated server did not create its one-time QA setup code.')
        owner=h.Transport()
        response=owner.call('auth/setup','POST',{'token':setup.group(1),'email':'studio-admin@example.test','full_name':'Studio QA','password':env['BOOTSTRAP_ADMIN_PASSWORD']})
        assert response['status']==201,response
        response=owner.call('auth/login','POST',{'email':'studio-admin@example.test','password':env['BOOTSTRAP_ADMIN_PASSWORD']})
        assert response['status']==200,response
        company=owner.call('mutate','POST',{'table':'companies','action':'create','data':{'name':'Studio QA Company'}})
        assert company['status']==200,company
        company_data=json.loads(company['text'])
        batch=owner.call('mutate','POST',{'table':'batches','action':'create','data':{
            'batch_name':'Studio QA Batch','status':'Active','start_date':min(TODAY,'2026-10-01'),'end_date':max(TODAY,'2026-10-14'),
            'session_dates':sorted(set([TODAY,'2026-10-01','2026-10-04','2026-10-05','2026-10-06','2026-10-07','2026-10-08','2026-10-11','2026-10-12','2026-10-13','2026-10-14'])),
            'capacity':10,'description':''}})
        assert batch['status']==200,batch
        batch_data=json.loads(batch['text'])
        trainee=owner.call('mutate','POST',{'table':'trainees','action':'create','data':{
            'trainee_name':'Studio QA Trainee','company_id':company_data['records'][0]['id'],
            'batch_id':batch_data['records'][0]['id'],'email':'','phone':'','job_title':'','notes':''}})
        assert trainee['status']==200,trainee
        trainee_data=json.loads(trainee['text'])

        with sync_playwright() as playwright:
            browser=playwright.chromium.launch(headless=True,args=['--no-sandbox'])
            context=browser.new_context(viewport={'width':1440,'height':1000})
            trainer=context.new_page();trainer.set_default_timeout(15000)
            errors=[];trainer.on('pageerror',lambda error:errors.append(str(error)))
            trainer.goto(h.BASE+'/trainer-activities/',wait_until='networkidle')
            expect(trainer.locator('#trainer-login')).to_be_visible()
            check('Standalone module serves its secure staff sign-in')
            trainer.locator('#trainer-login [name="email"]').fill('studio-admin@example.test')
            trainer.locator('#trainer-login [name="password"]').fill(env['BOOTSTRAP_ADMIN_PASSWORD'])
            trainer.locator('#trainer-login [type="submit"]').click()
            expect(trainer.get_by_role('heading',name="Turn today's lesson into a challenge.")).to_be_visible()
            expect(trainer.locator('.quiz-tile')).to_have_count(8)
            check('Trainer sees Academy Studio with eight curated, ready-to-run challenges')
            trainer.locator('[data-action="roleplay-open"]').click()
            expect(trainer.locator('.roleplay-setup')).to_be_visible()
            expect(trainer.locator('.roleplay-scenario-choice')).to_have_count(10)
            expect(trainer.locator('.roleplay-privacy-note')).to_contain_text('No learner data saved')
            check('Role-play Lab is directly reachable from Studio and explains its no-recording promise before use')
            screenshot('roleplay-lab-setup',trainer,full_page=False)
            ai_roleplay_requests=[]
            def mock_roleplay_ai(route):
                ai_roleplay_requests.append(route.request.post_data_json)
                route.fulfill(status=200,json={'scenario':{
                    'id':'ai-draft','title':'The rushed move','skill':'Client discovery','level':'Core',
                    'setup':'A client wants to move soon but has not explained the timing.',
                    'trainerBrief':'The client has a flexible move window and values a short commute. Reveal those details only if asked.',
                    'turns':[
                        {'clientLine':'I need to move soon, but I’m not sure where to start.','coachCue':'Ask what is driving the move and give the client time to explain.'},
                        {'clientLine':'I have a few options in mind. Can you tell me which is best?','coachCue':'Clarify their priorities before comparing options; do not choose for them.'},
                        {'clientLine':'That makes sense. What would you suggest we do next?','coachCue':'Reflect the client’s priority and agree a specific, client-approved next step.'}],
                    'lookFors':[{'id':'move-1','label':'Asks an open question before recommending'},{'id':'move-2','label':'Checks the client’s priority in their own words'},{'id':'move-3','label':'Agrees a clear next step with the client'}],
                    'avoid':'Do not promise an outcome, invent availability, or rush the client into a decision.',
                    'model':'I can help compare the options against what matters most to you. What would make a move feel manageable?',
                    'debrief':'Which question helped the client explain what mattered most?'
                },'source':'ai'})
            trainer.route('**/api/ai',mock_roleplay_ai)
            trainer.locator('.roleplay-ai-planner summary').click()
            trainer.locator('#roleplay-ai-notes').fill('Practise checking a client’s timing before suggesting a next step.')
            trainer.locator('[data-action="roleplay-ai-draft"]').click()
            expect(trainer.locator('#roleplay-ai-status')).to_contain_text('consent')
            check('Role-play AI does not send lesson notes before explicit consent',len(ai_roleplay_requests)==0)
            trainer.locator('#roleplay-ai-consent').check()
            trainer.locator('[data-action="roleplay-ai-draft"]').click()
            expect(trainer.locator('.roleplay-scenario-choice')).to_have_count(11)
            expect(trainer.locator('[data-scenario="ai-draft"]')).to_contain_text('TEMPORARY AI DRAFT')
            expect(trainer.locator('.roleplay-temporary-draft')).to_contain_text('TEMPORARY AND UNSAVED')
            expect(trainer.locator('.roleplay-selected-preview')).to_contain_text('The rushed move')
            expect(trainer.locator('#roleplay-ai-notes')).to_have_value('Practise checking a client’s timing before suggesting a next step.')
            expect(trainer.locator('#roleplay-ai-focus')).to_have_value('discovery')
            expect(trainer.locator('#roleplay-ai-consent')).not_to_be_checked()
            check('A consented AI scene appears as a temporary eleventh practice scene, clearly marked for trainer review',len(ai_roleplay_requests)==1 and ai_roleplay_requests[0]=={'kind':'draft-roleplay-scenario','consent':True,'focus_skill':'discovery','lesson_notes':'Practise checking a client’s timing before suggesting a next step.'})
            screenshot('roleplay-ai-draft',trainer,full_page=False)
            trainer.set_viewport_size({'width':390,'height':844})
            check('AI scene planner and selected draft fit a phone viewport without horizontal overflow',trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('roleplay-ai-draft-mobile',trainer,full_page=False)
            trainer.set_viewport_size({'width':1440,'height':1000})
            trainer.locator('[data-action="roleplay-start"]').click()
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('move soon')
            expect(trainer.locator('.roleplay-coach-lens')).to_have_count(0)
            expect(trainer.locator('.roleplay-trainer-brief')).not_to_have_attribute('open','')
            trainer.locator('[data-action="roleplay-next-turn"]').click()
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('few options')
            trainer.locator('[data-action="roleplay-next-turn"]').click()
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('suggest we do next')
            trainer.locator('[data-action="roleplay-reveal-coach"]').click()
            expect(trainer.locator('.roleplay-coach-lens')).to_be_visible()
            expect(trainer.locator('.roleplay-listen-for')).to_have_count(3)
            expect(trainer.locator('.roleplay-debrief')).to_contain_text('?')
            for move in trainer.locator('.roleplay-listen-for').all():move.click()
            expect(trainer.locator('.roleplay-complete')).to_contain_text('every coaching move spotted')
            trainer.get_by_role('button',name='Run another scene').click()
            expect(trainer.locator('.roleplay-scenario-choice')).to_have_count(11)
            expect(trainer.locator('.roleplay-scenario-choice[aria-pressed="true"]')).not_to_have_attribute('data-scenario','ai-draft')
            expect(trainer.locator('.roleplay-temporary-draft')).to_have_count(0)
            trainer.locator('[data-scenario="ai-draft"]').click()
            expect(trainer.locator('.roleplay-selected-preview')).to_contain_text('The rushed move')
            expect(trainer.locator('.roleplay-temporary-draft')).to_be_visible()
            check('AI scenes use the same line-by-line trainer brief, coaching lens, move celebration, retry-safe selection and scene cycling as curated role-plays')
            trainer.unroute('**/api/ai',mock_roleplay_ai)
            trainer.locator('[data-action="roleplay-exit"]').click()
            trainer.locator('[data-action="roleplay-open"]').click()
            expect(trainer.locator('.roleplay-scenario-choice')).to_have_count(10)
            trainer.locator('#roleplay-duration').select_option('30')
            trainer.locator('[data-action="roleplay-start"]').click()
            trainer.get_by_role('button',name='Start 30 sec').click()
            trainer.keyboard.press('Escape')
            expect(trainer.locator('#trainer-dialog')).not_to_be_visible()
            trainer.wait_for_timeout(900)
            expect(trainer.locator('#trainer-dialog')).not_to_be_visible()
            check('Escape closes a stand-alone role-play cleanly and does not leave a timer to reopen or mutate it')
            trainer.locator('.quiz-tile[data-activity-id="quiz-handoff"]').get_by_role('button',name='Assign to class').click()
            expect(trainer.locator('#assignment-form')).to_be_visible()
            expect(trainer.locator('#assignment-activity')).to_have_value('quiz-handoff')
            trainer.locator('#assignment-form').get_by_role('button',name='Cancel').click()
            trainer.locator('.quiz-tile[data-activity-id="quiz-trust"]').get_by_role('button',name='Host live').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            expect(trainer.locator('#room-activity')).to_have_value('quiz-trust')
            trainer.locator('#live-room-form').get_by_role('button',name='Cancel').click()
            check('Each challenge has one-click assignment and preselected live-host actions')
            trainer.get_by_role('button',name='Plan a session').first.click()
            expect(trainer.locator('#session-plan-form')).to_be_visible()
            trainer.locator('#plan-batch').select_option(batch_data['records'][0]['id'])
            trainer.locator('#plan-company').select_option(company_data['records'][0]['id'])
            trainer.locator('#plan-date').fill('2026-10-06')
            trainer.locator('#plan-title').fill('Discovery classroom lab')
            trainer.locator('#plan-focus').select_option('discovery')
            trainer.locator('#plan-activity').select_option('quiz-discovery')
            trainer.locator('#plan-duration').fill('30')
            ai_requests=[]
            def mock_session_ai(route):
                ai_requests.append(route.request.post_data_json)
                route.fulfill(status=200,json={'step_prompts':{
                    'spark':'Recall a question that helped a client explain why they are moving.',
                    'quest':'Play the challenge together. Commit to a choice before the trainer reveals the coaching takeaway.',
                    'huddle':'Which response protected the client’s goal, and what would you say in a real conversation?',
                    'exit':'Name one open question you will use in your next client conversation.'},'source':'ai'})
            trainer.route('**/api/ai',mock_session_ai)
            trainer.locator('#session-ai-notes').fill('Revisit open questions and the client’s timeline before suggesting a property.')
            trainer.locator('[data-action="session-ai-draft"]').click()
            expect(trainer.locator('#session-ai-status')).to_contain_text('consent')
            check('AI session co-planner does not send lesson notes before explicit consent',len(ai_requests)==0)
            trainer.locator('#session-ai-consent').check()
            trainer.locator('[data-action="session-ai-draft"]').click()
            expect(trainer.locator('#session-ai-status')).to_contain_text('AI draft ready')
            expect(trainer.locator('[data-step-prompt="spark"]')).to_have_value('Recall a question that helped a client explain why they are moving.')
            check('Consented AI session draft is editable, contains exactly four cues, and remains unsaved until plan submission',len(ai_requests)==1 and ai_requests[0]=={'kind':'draft-session-prompts','consent':True,'activity_id':'quiz-discovery','focus_skill':'discovery','lesson_notes':'Revisit open questions and the client’s timeline before suggesting a property.'} and trainer.locator('[data-step-prompt]').count()==4)
            trainer.unroute('**/api/ai',mock_session_ai)
            trainer.locator('#session-plan-form [type="submit"]').click()
            expect(trainer.locator('.session-plan-card')).to_contain_text('Discovery classroom lab')
            expect(trainer.locator('.session-plan-card .session-step')).to_have_count(4)
            session_card=trainer.locator('.session-plan-card').filter(has_text='Discovery classroom lab')
            expect(session_card.locator('.session-quiz-unlock')).to_contain_text('Oct 6')
            expect(session_card.locator('.session-assign-button')).to_have_count(0)
            check('A future session clearly shows its private-quiz unlock date without letting trainers assign early')
            trainer.get_by_role('button',name='Plan a session').first.click()
            trainer.locator('#plan-batch').select_option(batch_data['records'][0]['id'])
            trainer.locator('#plan-company').select_option(company_data['records'][0]['id'])
            trainer.locator('#plan-date').fill(TODAY)
            trainer.locator('#plan-title').fill('Session-day follow-up')
            trainer.locator('#plan-focus').select_option('discovery')
            trainer.locator('#plan-activity').select_option('quiz-discovery')
            trainer.locator('#plan-duration').fill('30')
            trainer.locator('#session-plan-form [type="submit"]').click()
            today_session=trainer.locator('.session-plan-card').filter(has_text='Session-day follow-up')
            expect(today_session.locator('.session-assign-button')).to_be_visible()
            future_plan_id=session_card.locator('.session-step-toggle[data-step="quest"]').get_attribute('data-plan')
            check('A second session scheduled for the current Cairo date is immediately ready for its one linked quiz')
            session_card.locator('.session-step-toggle[data-step="spark"]').click()
            expect(session_card.locator('.session-step-toggle[data-step="spark"]')).to_have_attribute('aria-pressed','true')
            trainer.reload(wait_until='domcontentloaded')
            session_card=trainer.locator('.session-plan-card').filter(has_text='Discovery classroom lab')
            expect(session_card.locator('.session-step-toggle[data-step="spark"]')).to_have_attribute('aria-pressed','true')
            trainer_peer=context.new_page();trainer_peer.set_default_timeout(15000);trainer_peer.on('pageerror',lambda error:errors.append(str(error)))
            trainer_peer.goto(h.BASE+'/trainer-activities/',wait_until='networkidle')
            peer_session_card=trainer_peer.locator('.session-plan-card').filter(has_text='Discovery classroom lab')
            expect(peer_session_card).to_be_visible()
            expect(peer_session_card.locator('.session-step-toggle[data-step="spark"]')).to_have_attribute('aria-pressed','true')
            expect(peer_session_card).to_contain_text('Recall a question that helped a client explain why they are moving.')
            check('A second signed-in trainer opens the same saved session plan from the shared workspace')
            session_card.locator('[data-action="session-run"]').click()
            expect(trainer.locator('#session-facilitator')).to_be_visible()
            expect(trainer.locator('#session-facilitator')).to_contain_text('Discovery classroom lab')
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 02')
            expect(trainer.locator('#session-run-clock')).to_be_visible()
            trainer.get_by_role('button',name='Start timer').click()
            expect(trainer.get_by_role('button',name='Pause timer')).to_be_visible()
            trainer.get_by_role('button',name='Pause timer').click()
            trainer.get_by_role('button',name='Reset',exact=True).click()
            expect(trainer.get_by_role('button',name='Start timer')).to_be_visible()
            trainer.locator('.session-run-stage').click()
            trainer.locator('.session-run-stage').press('ArrowRight')
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 03')
            trainer.locator('.session-run-stage').press('ArrowLeft')
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 02')
            trainer.locator('.session-run-stage').press('ArrowLeft')
            expect(trainer.locator('.session-run-stage-copy p')).to_have_text('Recall a question that helped a client explain why they are moving.')
            check('A reviewed custom facilitator prompt persists into the full-screen class experience')
            trainer.locator('.session-run-stage').press('ArrowRight')
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 02')
            trainer.locator('.session-run-stage').press('Space')
            expect(trainer.get_by_role('button',name='Pause timer')).to_be_visible()
            trainer.wait_for_timeout(1100)
            trainer.locator('.session-run-stage').press('Space')
            expect(trainer.get_by_role('button',name='Resume timer')).to_be_visible()
            trainer.get_by_role('button',name='Fullscreen').click()
            trainer.wait_for_timeout(200)
            check('Facilitator presentation enters native fullscreen and supports arrow/space keyboard controls',trainer.evaluate('document.fullscreenElement === document.documentElement'))
            trainer.get_by_role('button',name='Exit fullscreen').click()
            trainer.wait_for_timeout(100)
            check('Facilitator can leave native fullscreen cleanly',trainer.evaluate('document.fullscreenElement === null'))
            trainer.get_by_role('button',name='Reset',exact=True).click()
            screenshot('session-facilitator-desktop',trainer,full_page=False)
            trainer.locator('.session-run-challenge [data-action="live-room"]').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            expect(trainer.locator('#room-activity')).to_have_value('quiz-discovery')
            check('Live-challenge handoff retains its full-screen room presentation shell', 'live-room-dialog' in trainer.locator('#trainer-dialog').get_attribute('class'))
            trainer.locator('#live-room-form').get_by_role('button',name='Cancel').click()
            session_card.locator('[data-action="session-run"]').click()
            expect(trainer.locator('.session-run-stage')).to_be_visible()
            pulse_before=json.loads(owner.call('state')['text'])
            trainer.get_by_role('button',name='Run an anonymous class pulse').click()
            expect(trainer.locator('#session-pulse-form')).to_be_visible()
            expect(trainer.locator('.pulse-choice-row')).to_have_count(3)
            trainer.locator('[data-action="pulse-choice-add"]').click()
            expect(trainer.locator('.pulse-choice-row')).to_have_count(4)
            trainer.locator('.pulse-choice-row').last.locator('[data-action="pulse-choice-remove"]').click()
            expect(trainer.locator('.pulse-choice-row')).to_have_count(3)
            trainer.locator('#session-pulse-form [type="submit"]').click()
            expect(trainer.locator('.live-pulse-shell')).to_be_visible()
            expect(trainer.locator('.pulse-host-question h2')).not_to_be_empty()
            check('Every facilitator step can launch a one-question pulse with editable prompt, two-to-five answer options, and a timer')
            pulse_link=trainer.locator('.room-join-panel code').inner_text()
            pulse_code=trainer.locator('.room-join-code').inner_text()
            pulse_phone_contexts=[];pulse_phones=[]
            for index in range(3):
                phone_context=browser.new_context(viewport={'width':390,'height':844})
                pulse_phone_contexts.append(phone_context)
                phone=phone_context.new_page();phone.set_default_timeout(15000);phone.on('pageerror',lambda error:errors.append(str(error)))
                phone.goto(pulse_link,wait_until='networkidle')
                expect(phone.locator('#live-phone-join')).to_be_visible()
                check('Anonymous pulse entry contains no trainee name or team fields',phone.locator('#live-phone-join [name="nickname"]').count()==0 and phone.locator('#live-phone-join [name="team_no"]').count()==0)
                phone.get_by_role('button',name='Join anonymously').click()
                expect(phone.locator('.pulse-play-card')).to_be_visible()
                expect(phone.locator('.pulse-anon-promise')).to_have_count(0)
                expect(phone.locator('.pulse-phone-option')).to_have_count(3)
                pulse_phones.append(phone)
            expect(trainer.locator('.pulse-response-orbit small')).to_contain_text('3 joined',timeout=10000)
            check('Pulse learner view fits a phone viewport without horizontal overflow',pulse_phones[0].evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            trainer.get_by_role('button',name='Start 30-second timer').click()
            expect(pulse_phones[0].locator('.live-phone-timer')).to_be_visible(timeout=10000)
            trainer.get_by_role('button',name='Pause timer').click()
            check('The optional pulse timer synchronizes to learner phones')
            pulse_phones[0].locator('.pulse-phone-option').nth(0).click()
            pulse_phones[1].locator('.pulse-phone-option').nth(1).click()
            expect(trainer.locator('.pulse-results-private')).to_contain_text('2 of 3',timeout=10000)
            check('Pulse result distribution stays concealed below the three-response privacy threshold')
            pulse_phones[2].locator('.pulse-phone-option').nth(1).click()
            expect(trainer.locator('.pulse-result-list')).to_be_visible(timeout=10000)
            check('Trainer gets live aggregate counts only after the minimum privacy threshold, without a response-by-person feed',trainer.locator('.room-reveal-feed').count()==0 and trainer.locator('.pulse-result-list').inner_text().find('2 responses')>=0)
            check('Learner phones cannot inspect the distribution before the trainer reveals it',all(phone.locator('.pulse-result-list').count()==0 for phone in pulse_phones))
            trainer.get_by_role('button',name='Reveal class pattern').click()
            expect(pulse_phones[0].locator('.pulse-result-list')).to_be_visible(timeout=10000)
            expect(pulse_phones[0].locator('.pulse-result-list')).to_contain_text('2 - 67%')
            expect(pulse_phones[0].locator('.pulse-result-list')).to_contain_text('1 - 33%')
            check('Reveal synchronizes an anonymous, ungraded aggregate pattern to all learner phones')
            screenshot('session-class-pulse',trainer,full_page=False)
            trainer.once('dialog',lambda popup:popup.accept())
            trainer.get_by_role('button',name='Finish pulse & return to session').last.click()
            expect(trainer.locator('.session-run-stage')).to_be_visible()
            expect(trainer.locator('.session-run-overview')).to_be_visible()
            for phone in pulse_phones:expect(phone.locator('.pulse-finish-card')).to_be_visible(timeout=10000)
            pulse_after=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:assert pulse_after[key]==pulse_before[key],f'class pulse changed {key}'
            for phone_context in pulse_phone_contexts:phone_context.close()
            check('Closing the pulse ends the phone room, returns the facilitator to the same run-of-show, and leaves Academy records untouched')
            trainer.get_by_role('button',name='Mark step complete').click()
            expect(trainer.locator('.session-run-overview')).to_contain_text('2 / 4 steps complete')
            expect(session_card.locator('.session-step-toggle[data-step="quest"]')).to_have_attribute('aria-pressed','true')
            expect(peer_session_card.locator('.session-step-toggle[data-step="quest"]')).to_have_attribute('aria-pressed','true',timeout=10000)
            check('Facilitation mode runs and resets a presenter-only timer, hands off to its linked live challenge, and streams saved step completion to the second trainer')
            trainer.get_by_role('button',name='Next step').click()
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 03')
            roleplay_before=json.loads(owner.call('state')['text'])
            trainer.locator('.session-run-challenge [data-action="roleplay-open"]').click()
            expect(trainer.locator('.roleplay-setup')).to_be_visible()
            trainer.locator('[data-scenario="price-objection"]').click()
            expect(trainer.locator('.roleplay-selected-preview')).to_contain_text('That feels expensive')
            trainer.locator('[data-format="pair"]').click()
            expect(trainer.locator('[data-format="pair"]')).to_have_attribute('aria-pressed','true')
            trainer.locator('#roleplay-duration').select_option('30')
            trainer.locator('[data-action="roleplay-start"]').click()
            expect(trainer.locator('.roleplay-live-heading')).to_contain_text('Partner A advises while Partner B plays the client')
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('feels expensive')
            expect(trainer.locator('.roleplay-coach-lens')).to_have_count(0)
            expect(trainer.locator('.roleplay-trainer-brief')).not_to_have_attribute('open','')
            trainer.get_by_role('button',name='Start 30 sec').click()
            expect(trainer.get_by_role('button',name='Pause timer')).to_be_visible()
            trainer.get_by_role('button',name='Pause timer').click()
            expect(trainer.locator('.roleplay-clock')).to_be_visible()
            trainer.locator('[data-action="roleplay-next-turn"]').click()
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('smaller')
            trainer.locator('[data-action="roleplay-next-turn"]').click()
            expect(trainer.locator('.roleplay-client-stage blockquote')).to_contain_text('rush')
            expect(trainer.locator('.roleplay-coach-lens')).to_have_count(0)
            trainer.locator('[data-action="roleplay-reveal-coach"]').click()
            expect(trainer.locator('.roleplay-coach-lens')).to_be_visible()
            expect(trainer.locator('.roleplay-listen-for')).to_have_count(3)
            expect(trainer.locator('.roleplay-debrief')).to_contain_text('?')
            trainer.locator('.roleplay-listen-for').nth(0).click()
            trainer.locator('.roleplay-listen-for').nth(1).click()
            expect(trainer.locator('.roleplay-coins')).to_contain_text('2 / 3 moves spotted')
            trainer.locator('.roleplay-listen-for').nth(2).click()
            expect(trainer.locator('.roleplay-complete')).to_contain_text('every coaching move spotted')
            screenshot('roleplay-lab-full-house',trainer)
            check('A client conversation reveals one line at a time; coaching stays hidden until the final turn and the in-room full-house celebration is temporary')
            trainer.get_by_role('button',name='Try the scene again').click()
            expect(trainer.locator('.roleplay-live-heading')).to_contain_text('REP 2')
            expect(trainer.locator('.roleplay-live-heading')).to_contain_text('Partner B advises while Partner A plays the client')
            expect(trainer.locator('.roleplay-clock')).to_contain_text('00:30')
            trainer.locator('[data-action="roleplay-setup"]').click()
            trainer.locator('[data-action="roleplay-random"]').click()
            expect(trainer.locator('.roleplay-scenario-choice[aria-pressed="true"]')).to_have_count(1)
            check('Retry resets a second practice rep and the surprise picker chooses a different client scene')
            trainer.set_viewport_size({'width':390,'height':844})
            trainer.locator('[data-action="roleplay-start"]').click()
            check('Role-play setup and live client prompt fit a phone viewport without horizontal overflow',trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('roleplay-lab-mobile',trainer,full_page=False)
            trainer.get_by_role('button',name='Back to session').click()
            expect(trainer.locator('.session-run-stage')).to_be_visible()
            expect(trainer.locator('.session-run-step-kicker')).to_contain_text('STEP 03')
            roleplay_after=json.loads(owner.call('state')['text'])
            for key in roleplay_before:assert roleplay_after[key]==roleplay_before[key],f'role-play changed Academy state {key}'
            check('Role-play returns to the same coaching huddle and changes no server-side Academy state')
            trainer.set_viewport_size({'width':1440,'height':1000})
            trainer.locator('#trainer-dialog [data-action="dialog-close"]').click()
            check('Facilitator can navigate between planned activities and leave the run without changing trainee records')
            trainer.set_viewport_size({'width':390,'height':844})
            session_card.locator('[data-action="session-run"]').click()
            expect(trainer.locator('.session-run-stage')).to_be_visible()
            check('Facilitation mode shows every planned step on a phone without page-level horizontal overflow',trainer.locator('.session-run-step').count()==4 and trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('session-facilitator-mobile',trainer,full_page=False)
            trainer.locator('#trainer-dialog [data-action="dialog-close"]').click()
            check('The shared session board stays usable on a phone without horizontal overflow',trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            trainer.set_viewport_size({'width':1440,'height':1000})
            session_card.locator('.session-host-button').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            expect(trainer.locator('#room-activity')).to_have_value('quiz-discovery')
            trainer.locator('#live-room-form').get_by_role('button',name='Cancel').click()
            check('A trainer creates a shared four-part session board, checks off work, resumes it after reload, and hosts its linked challenge')
            screenshot('trainer-studio-desktop',trainer)
            baseline_assignments=len(json.loads(owner.call('activities')['text'])['assignments'])
            trainer.get_by_role('button',name='Host a live room').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            trainer.locator('#room-activity').select_option('quiz-discovery')
            trainer.locator('#room-team-one').fill('Atlas Crew')
            trainer.locator('#room-team-two').fill('Orbit Crew')
            trainer.locator('#live-room-form [type="submit"]').click()
            expect(trainer.locator('.room-question h2')).to_contain_text('two-bedroom place soon')
            check('Trainer launches a live team room from a staff-only answer deck')
            trainer.set_viewport_size({'width':390,'height':844})
            check('Live room fits a narrow classroom screen without horizontal overflow',trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            trainer.set_viewport_size({'width':1440,'height':1000})
            screenshot('live-team-room-question',trainer)
            trainer.get_by_role('button',name='Start 30-second timer').click()
            trainer.get_by_role('button',name='Pause timer').click()
            expect(trainer.locator('.room-option-correct')).to_have_count(0)
            trainer.get_by_role('button',name='Reveal coaching answer').click()
            expect(trainer.locator('.room-option-correct')).to_contain_text('Ask what prompted the move')
            trainer.locator('.room-team').nth(0).get_by_role('button',name='Award 100 points').click()
            expect(trainer.locator('.room-team').nth(0)).to_contain_text('100')
            trainer.get_by_role('button',name='Undo last point').click()
            expect(trainer.locator('.room-team').nth(0)).to_contain_text('0')
            trainer.locator('.room-team').nth(1).get_by_role('button',name='Award 100 points').click()
            trainer.get_by_role('button',name='Next round').click()
            expect(trainer.locator('.room-round-meta')).to_contain_text('ROUND 2 / 5')
            screenshot('live-team-room-reveal',trainer)
            for round_index in range(2,6):
                trainer.get_by_role('button',name='Reveal coaching answer').click()
                expect(trainer.locator('.room-coaching')).to_be_visible()
                trainer.get_by_role('button',name='Finish room' if round_index==5 else 'Next round').click()
            expect(trainer.locator('.room-finish h2')).to_contain_text('Orbit Crew takes the round')
            trainer.get_by_role('button',name='Play another set').click()
            expect(trainer.locator('.room-round-meta')).to_contain_text('ROUND 1 / 5')
            expect(trainer.locator('.room-team-score').nth(1)).to_contain_text('0')
            trainer.get_by_role('button',name='Exit room').click()
            expect(trainer.locator('#trainer-dialog')).not_to_be_visible()
            assert len(json.loads(owner.call('activities')['text'])['assignments'])==baseline_assignments
            check('Live team points, timer and answer reveal leave all Academy records unchanged')

            sequence_before=json.loads(owner.call('state')['text'])
            trainer.get_by_role('button',name='Host a live room').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            trainer.locator('#room-activity').select_option('sequence-sprint')
            trainer.locator('#room-team-one').fill('Care Crew')
            trainer.locator('#room-team-two').fill('Client First')
            trainer.locator('#room-timer').select_option('0')
            trainer.locator('[name="phone_enabled"]').check()
            trainer.locator('#live-room-form [type="submit"]').click()
            expect(trainer.locator('.sequence-room-question h2')).to_contain_text('two-bedroom home soon')
            expect(trainer.locator('.sequence-step-list-host .sequence-step-card')).to_have_count(3)
            expect(trainer.locator('.room-distribution')).to_have_count(0)
            sequence_link=trainer.locator('.room-join-panel code').inner_text()
            sequence_context=browser.new_context(viewport={'width':390,'height':844})
            sequence_phone=sequence_context.new_page();sequence_phone.set_default_timeout(15000);sequence_phone.on('pageerror',lambda error:errors.append(str(error)))
            sequence_phone.goto(sequence_link,wait_until='networkidle')
            sequence_phone.locator('[name="nickname"]').fill('Order Builder')
            sequence_phone.locator('input[name="team_no"][value="1"]').check()
            sequence_phone.locator('#live-phone-join [type="submit"]').click()
            expect(sequence_phone.locator('.live-phone-question h2')).to_contain_text('two-bedroom home soon')
            expect(sequence_phone.locator('.sequence-step-list-phone .sequence-step-card')).to_have_count(3)
            expect(sequence_phone.locator('.live-phone-option')).to_have_count(0)
            expect(sequence_phone.locator('.live-confidence-check')).to_be_visible()
            sequence_phone.get_by_role('button',name='Ready to stand by it').click()
            sequence_phones=[sequence_phone]
            for index, (nickname, confidence, team_no) in enumerate([
                ('Care Partner','Ready to stand by it',2),
                ('Client Advocate','Still thinking',1),
            ],start=2):
                phone=sequence_context.new_page();phone.set_default_timeout(15000);phone.on('pageerror',lambda error:errors.append(str(error)))
                phone.goto(sequence_link,wait_until='networkidle')
                phone.locator('[name="nickname"]').fill(nickname)
                phone.locator(f'input[name="team_no"][value="{team_no}"]').check()
                phone.locator('#live-phone-join [type="submit"]').click()
                expect(phone.locator('.live-confidence-check')).to_be_visible()
                phone.get_by_role('button',name=confidence).click()
                sequence_phones.append(phone)
            sequence_phone.locator('.sequence-step-list-phone .sequence-step-card').nth(0).get_by_role('button',name=re.compile('Move .* later')).click()
            sequence_phone.locator('.sequence-step-list-phone .sequence-step-card').nth(1).get_by_role('button',name=re.compile('Move .* later')).click()
            ordered_steps=sequence_phone.locator('.sequence-step-list-phone .sequence-step-card')
            expect(ordered_steps.nth(0)).to_contain_text('Ask what is driving the move')
            expect(ordered_steps.nth(1)).to_contain_text('Clarify timing and flexibility')
            expect(ordered_steps.nth(2)).to_contain_text('Agree on a useful next step together')
            sequence_phone.wait_for_timeout(2200)
            expect(sequence_phone.locator('.sequence-step-list-phone .sequence-step-card').nth(0)).to_contain_text('Ask what is driving the move')
            sequence_phone.get_by_role('button',name='Lock my order').click()
            expect(sequence_phone.locator('.live-answer-locked')).to_contain_text('Your order is in')
            for phone in sequence_phones[1:]:
                phone.get_by_role('button',name='Lock my order').click()
            expect(trainer.locator('.sequence-response-count')).to_contain_text('3 of 3 players submitted an order',timeout=10000)
            expect(trainer.locator('.sequence-room-question')).not_to_contain_text('COACHING TAKEAWAY')
            sequence_phone.reload(wait_until='domcontentloaded')
            expect(sequence_phone.locator('.sequence-step-list-phone .sequence-step-card').nth(0)).to_contain_text('Ask what is driving the move')
            expect(sequence_phone.get_by_role('button',name='Update my order')).to_be_visible()
            expect(sequence_phone.get_by_role('button',name='Ready to stand by it')).to_have_attribute('aria-pressed','true')
            check('Sequence Sprint runs a phone-first ordered-step round without exposing the answer or presenting fake multiple-choice options')
            check('A trainee can reorder steps accessibly, keep an unsent draft through live polling, and restore both the submitted order and private confidence choice after reconnecting')
            check('Sequence Sprint phone layout has no horizontal overflow',sequence_phone.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('sequence-sprint-phone',sequence_phone,full_page=False)
            trainer.get_by_role('button',name='Reveal coaching order').click()
            expect(sequence_phone.locator('.live-phone-feedback')).to_contain_text('+100 room points',timeout=10000)
            expect(sequence_phone.locator('.live-sequence-reveal .sequence-step-card').nth(0)).to_contain_text('Ask what is driving the move')
            expect(trainer.locator('.sequence-room-question .sequence-step-list-host .sequence-step-card').nth(0)).to_contain_text('Ask what is driving the move')
            expect(trainer.locator('.live-classroom-debrief')).to_contain_text('never a formal grade')
            expect(trainer.locator('.live-debrief-signal')).to_contain_text('PAUSE AND REBUILD')
            expect(trainer.locator('.live-classroom-debrief')).to_contain_text('CONFIDENCE, THEN ACCURACY')
            expect(trainer.locator('.live-debrief-calibration')).to_contain_text('2 ready to stand by it')
            expect(trainer.locator('.live-debrief-calibration')).to_contain_text('1 still thinking')
            expect(trainer.locator('.live-debrief-calibration')).to_contain_text('Need 3+ in this group for an accuracy signal')
            expect(trainer.locator('.room-team').nth(0)).to_contain_text('100')
            check('The coach reveal shows the sequence, gives phone feedback, awards temporary points, and displays only a privacy-thresholded confidence aggregate')
            trainer.once('dialog',lambda popup:popup.accept())
            trainer.get_by_role('button',name='End phone room').click()
            expect(sequence_phone.locator('.live-finish-card')).to_contain_text('ROOM ENDED',timeout=10000)
            sequence_after=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:
                assert sequence_after[key]==sequence_before[key],f'Sequence Sprint changed Academy state {key}'
            assert len(json.loads(owner.call('activities')['text'])['assignments'])==baseline_assignments
            check('Sequence Sprint leaves trainee, assessment, attendance and assignment records untouched')
            sequence_context.close()

            trainer.get_by_role('button',name='Host a live room').click()
            trainer.locator('#room-activity').select_option('quiz-discovery')
            trainer.locator('#room-team-count').select_option('4')
            trainer.locator('#room-team-one').fill('Atlas Crew')
            trainer.locator('#room-team-two').fill('Orbit Crew')
            trainer.locator('#room-team-3').fill('Comet Crew')
            trainer.locator('#room-team-4').fill('Nebula Crew')
            trainer.locator('#room-timer').select_option('20')
            trainer.locator('[name="phone_enabled"]').check()
            trainer.locator('#live-room-form [type="submit"]').click()
            expect(trainer.locator('.room-join-panel')).to_be_visible()
            phone_link=trainer.locator('.room-join-panel code').inner_text()
            phone_context=browser.new_context(viewport={'width':390,'height':844})
            phone=phone_context.new_page();phone.set_default_timeout(15000);phone.on('pageerror',lambda error:errors.append(str(error)))
            phone.goto(phone_link,wait_until='networkidle')
            expect(phone.locator('#live-phone-join')).to_be_visible()
            expect(phone.locator('.live-team-choice')).to_have_count(4)
            phone.locator('[name="nickname"]').fill('Orbit Phone')
            phone.locator('input[name="team_no"][value="4"]').check()
            phone.locator('#live-phone-join [type="submit"]').click()
            expect(phone.locator('.live-phone-question h2')).to_contain_text('two-bedroom place soon')
            expect(phone.locator('.live-player-status')).to_contain_text('LIVE CLASSROOM')
            expect(phone.locator('.live-score-strip > div')).to_have_count(4)
            expect(trainer.locator('.room-team').nth(3)).to_contain_text('Orbit Phone',timeout=10000)
            check('A learner joins the fourth team in the same live room from a separate phone browser')
            check('Four-team host board keeps every full team name readable',trainer.evaluate("Array.from(document.querySelectorAll('.room-team h3')).every(el=>el.scrollWidth<=el.clientWidth)"))
            screenshot('live-four-team-board',trainer)
            screenshot('live-four-team-phone',phone)
            trainer.get_by_role('button',name='Start 20-second timer').click()
            expect(phone.locator('.live-phone-timer')).to_be_visible()
            trainer.get_by_role('button',name='Pause timer').click()
            phone.locator('.live-phone-option').nth(0).click()
            phone.locator('.live-phone-option').nth(1).click()
            expect(trainer.locator('.room-response-pulse')).to_contain_text('1 of 1 players answered',timeout=10000)
            expect(trainer.locator('.room-distribution')).to_contain_text('B 1')
            check('Trainer sees anonymous answer totals, while the phone cannot see the answer key')
            trainer.get_by_role('button',name='Reveal coaching answer').click()
            expect(phone.locator('.live-phone-feedback')).to_contain_text('+100 room points',timeout=10000)
            expect(phone.locator('.live-phone-feedback')).to_contain_text('Understand the motivation and timeline')
            expect(trainer.locator('.room-team').nth(3)).to_contain_text('100')
            expect(trainer.locator('.live-classroom-debrief')).to_contain_text('SMALL-ROOM SIGNAL')
            expect(trainer.locator('.live-classroom-debrief')).to_contain_text('never a formal grade')
            expect(trainer.locator('.live-debrief-signal')).not_to_contain_text('%')
            check('Reveal unlocks coaching feedback and awards temporary points to the correct phone player')
            old_join_code=trainer.locator('.room-join-code').inner_text()
            trainer.reload(wait_until='domcontentloaded')
            trainer.get_by_role('button',name=re.compile('Resume live room')).click(timeout=15000)
            trainer.locator('.live-room-resume-row').filter(has_text='Discovery Sprint').click(timeout=10000)
            expect(trainer.locator('.room-join-panel')).to_be_visible()
            check('Trainer can recover an in-progress room after reloading the Academy page')
            check('Resuming preserves the fourth team, current round and earned temporary points',trainer.locator('.room-team').nth(3).inner_text().find('100')>=0)
            check('Resume rotates the join code so an old invite cannot admit new players',trainer.locator('.room-join-code').inner_text()!=old_join_code)
            phone.reload(wait_until='domcontentloaded')
            expect(phone.locator('.live-phone-feedback')).to_contain_text('+100 room points',timeout=10000)
            check('An already-joined learner reconnects through the private seat token after code rotation')
            correct_choices=[1,2,1,1,2]
            for round_index in range(1,5):
                trainer.get_by_role('button',name='Next round').click()
                expect(phone.locator('.live-phone-progress')).to_contain_text(f'ROUND {round_index+1} OF 5',timeout=10000)
                phone.locator('.live-phone-option').nth(correct_choices[round_index]).click()
                expect(trainer.locator('.room-response-pulse')).to_contain_text('1 of 1 players answered',timeout=10000)
                trainer.get_by_role('button',name='Reveal coaching answer').click()
                expect(phone.locator('.live-phone-feedback')).to_contain_text('+',timeout=10000)
            trainer.get_by_role('button',name='Finish room').click()
            expect(phone.locator('.live-finish-card')).to_contain_text('750 temporary room points',timeout=10000)
            expect(trainer.locator('.room-team-label').first).to_contain_text('PLACE 01')
            expect(trainer.locator('.room-team').first).to_contain_text('Nebula Crew')
            expect(phone.locator('.live-finish-card')).to_contain_text('None of these points change Academy XP')
            trainer.get_by_role('button',name='Play another set').click()
            expect(phone.locator('.live-phone-progress')).to_contain_text('ROUND 1 OF 5',timeout=10000)
            expect(phone.locator('.live-score-strip').nth(0)).to_contain_text('0 pts',timeout=10000)
            check('Room recap shows streak bonuses, and replay resets only temporary room points')
            trainer.on('dialog',lambda popup:popup.accept())
            trainer.get_by_role('button',name='End phone room').click()
            expect(phone.locator('.live-finish-card')).to_contain_text('ROOM ENDED',timeout=10000)
            check('Trainer can close the room and disconnect every learner phone')
            phone_context.close()

            trainer.set_viewport_size({'width':390,'height':844})
            check('Trainer dashboard fits a narrow mobile screen without horizontal overflow',trainer.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            trainer.set_viewport_size({'width':1440,'height':1000})
            scheduled_card=trainer.locator('.session-plan-card').filter(has_text='Session-day follow-up')
            expect(scheduled_card.locator('.session-assign-button')).to_be_visible()
            records_before_session_quiz=json.loads(owner.call('state')['text'])
            session_plan_id=scheduled_card.locator('.session-step-toggle[data-step="quest"]').get_attribute('data-plan')
            scheduled_card.locator('.session-assign-button').click()
            expect(trainer.locator('#assignment-form')).to_be_visible()
            expect(trainer.locator('#assignment-batch')).to_have_value(batch_data['records'][0]['id'])
            expect(trainer.locator('#assignment-company')).to_have_value(company_data['records'][0]['id'])
            expect(trainer.locator('#assignment-activity')).to_have_value('quiz-discovery')
            expect(trainer.locator('#assignment-due')).to_have_value(TODAY)
            expect(trainer.locator('#assignment-instructions')).to_have_value(re.compile('Session follow-up'))
            expect(trainer.locator('#roster-list input[type="checkbox"]:checked')).to_have_count(1)
            check('On the scheduled session day, the linked challenge opens as a prefilled private class quiz for that company roster')
            trainer.locator('#assignment-form [type="submit"]').click()
            expect(trainer.locator('#links-content')).to_be_visible(timeout=15000)
            expect(trainer.locator('.private-link-row')).to_have_count(1)
            expect(trainer.locator('.private-link-row')).to_contain_text('Studio QA Trainee')
            link=trainer.locator('.private-link-row a').get_attribute('href')
            assert link and re.search(r'#/learner/[A-Za-z0-9_-]{43}$',link),link
            trainer.locator('#trainer-dialog [data-action="dialog-close"]').click()
            records_after_session_quiz=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:
                assert records_after_session_quiz[key]==records_before_session_quiz[key],f'scheduled quiz changed {key}'
            plan_after_session_quiz=next(plan for plan in json.loads(owner.call('activities/session-plans')['text'])['plans'] if plan['id']==session_plan_id)
            linked_assignment=next(assignment for assignment in json.loads(owner.call('activities')['text'])['assignments'] if assignment['due_date']==TODAY)
            assert plan_after_session_quiz['linked_assignment_id']==linked_assignment['id']
            duplicate=owner.call('activities/assign','POST',{'batch_id':batch_data['records'][0]['id'],'activity_id':'quiz-discovery','due_date':TODAY,'instructions':'Duplicate attempt','trainee_ids':[trainee_data['records'][0]['id']],'session_plan_id':session_plan_id})
            assert duplicate['status']==409,duplicate
            early=owner.call('activities/assign','POST',{'batch_id':batch_data['records'][0]['id'],'activity_id':'quiz-discovery','due_date':'2026-10-06','instructions':'Too early','trainee_ids':[trainee_data['records'][0]['id']],'session_plan_id':future_plan_id})
            assert early['status']==409,early
            trainer_peer.reload(wait_until='domcontentloaded')
            linked_session=trainer_peer.locator('.session-plan-card').filter(has_text='Session-day follow-up')
            expect(linked_session.locator('.session-assignment-linked')).to_be_visible()
            expect(linked_session.locator('.session-assign-button')).to_have_count(1)
            linked_session.locator('.session-assignment-linked').click()
            expect(trainer_peer.locator('.assignment-card').filter(has_text='Discovery Sprint')).to_be_visible()
            check('Session quiz automatically prepares one secure private learner link and leaves attendance and formal assessments untouched')

            learner=context.new_page();learner.set_default_timeout(15000);learner.on('pageerror',lambda error:errors.append(str(error)))
            learner.goto(link,wait_until='networkidle')
            expect(learner.get_by_role('heading',name='Discovery Sprint')).to_be_visible()
            expect(learner.get_by_text('Studio QA Trainee')).to_be_visible()
            check('Private link opens only its assigned trainee challenge, without a staff login')
            screenshot('trainee-challenge-intro',learner)
            learner.get_by_role('button',name='Study warm-up').click()
            expect(learner.locator('.study-card')).to_be_visible()
            expect(learner.locator('.study-progress')).to_have_attribute('aria-valuenow','1')
            expect(learner.locator('.study-progress')).to_have_class(re.compile(r'study-width-40'))
            learner.set_viewport_size({'width':390,'height':844})
            check('Active-recall warm-up progress is accessible and fits a phone screen',learner.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            learner.set_viewport_size({'width':1440,'height':1000})
            learner.get_by_role('button',name='Reveal takeaway').click()
            expect(learner.locator('.study-card')).to_contain_text('Ask what prompted the move')
            screenshot('trainee-active-recall',learner)
            learner.get_by_role('button',name='Revisit once').click()
            expect(learner.locator('.study-card')).to_contain_text('Separate must-haves from preferences')
            learner.get_by_role('button',name='Reveal takeaway').click()
            learner.get_by_role('button',name='Got it').click()
            expect(learner.locator('.study-card')).to_contain_text('Close the loop')
            learner.get_by_role('button',name='Reveal takeaway').click()
            learner.get_by_role('button',name='Got it').click()
            expect(learner.locator('.study-room')).to_contain_text('SECOND LOOK')
            learner.get_by_role('button',name='Reveal takeaway').click()
            learner.get_by_role('button',name='Still fuzzy').click()
            expect(learner.get_by_role('heading',name='Ready for the challenge?')).to_be_visible()
            expect(learner.locator('.study-self-check')).to_contain_text('2 of 3 cards felt clear')
            expect(learner.locator('.study-focus')).to_contain_text('Start with the story')
            screenshot('trainee-study-recap',learner)
            check('Active recall revisits learner-selected tricky cards once and carries remaining focus forward privately')
            learner.get_by_role('button',name='Review the cards again').click()
            expect(learner.locator('.study-room')).to_contain_text('CARD 1 OF 3')
            learner.get_by_role('button',name='Skip to challenge').click()
            check('Trainee can restart the optional study warm-up or jump straight to the quiz')

            correct_choices=[1,2,1,1,2]
            learner.get_by_role('button',name='Reveal hint').click()
            expect(learner.locator('.revealed-hint')).to_contain_text('Learn why the move matters')
            screenshot('trainee-hint-state',learner)
            learner.locator('.answer-option').nth(correct_choices[0]).click()
            learner.get_by_role('button',name='Next round').click()
            expect(learner.locator('.quiz-progress-meta')).to_contain_text('ROUND 2 OF 5')
            expect(learner.locator('.quiz-draft-status')).to_contain_text('Progress saved',timeout=10000)
            learner.reload(wait_until='networkidle')
            expect(learner.locator('.quiz-resume-banner')).to_contain_text('1 of 5 rounds answered')
            expect(learner.get_by_role('button',name='Continue round 2')).to_be_visible()
            learner.set_viewport_size({'width':390,'height':844})
            check('The saved-progress resume card fits a narrow phone without horizontal overflow',learner.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            learner.set_viewport_size({'width':1440,'height':1000})
            learner.get_by_role('button',name='Continue round 2').click()
            expect(learner.locator('.quiz-progress-meta')).to_contain_text('ROUND 2 OF 5')
            learner.get_by_role('button',name='Previous').click()
            expect(learner.locator('.revealed-hint')).to_contain_text('Learn why the move matters')
            expect(learner.locator('.answer-option input:checked')).to_have_value(str(correct_choices[0]))
            learner.get_by_role('button',name='Next round').click()
            expect(learner.locator('.quiz-draft-status')).to_contain_text('Progress saved',timeout=10000)
            stale_learner=context.new_page();stale_learner.set_default_timeout(15000);stale_learner.on('pageerror',lambda error:errors.append(str(error)))
            stale_learner.goto(link,wait_until='networkidle')
            stale_learner.get_by_role('button',name='Continue round 2').click()
            learner.locator('.answer-option').nth(correct_choices[1]).click()
            learner.get_by_role('button',name='Next round').click()
            expect(learner.locator('.quiz-draft-status')).to_contain_text('Progress saved',timeout=10000)
            stale_learner.locator('.answer-option').nth(0).click()
            stale_learner.get_by_role('button',name='Next round').click()
            expect(stale_learner.locator('.quiz-draft-status')).to_contain_text('Reload to continue',timeout=10000)
            stale_learner.close()
            check('A mid-quiz reload resumes the saved round, answer and coaching-hint choice privately, while an older open tab cannot overwrite newer work')
            for index in range(2,len(correct_choices)):
                choice=correct_choices[index]
                learner.locator('.answer-option').nth(choice).click()
                action='Finish challenge' if index==len(correct_choices)-1 else 'Next round'
                learner.get_by_role('button',name=re.compile(action)).click()
            expect(learner.get_by_role('heading',name='Precision player')).to_be_visible()
            expect(learner.locator('.score-orbit')).to_contain_text('100')
            expect(learner.locator('.result-row').first).to_contain_text('+70 XP')
            expect(learner.locator('.skill-signals')).to_contain_text('Client discovery')
            check('Quiz is server-graded and shows score, XP and answer-by-answer coaching review')
            screenshot('trainee-result',learner)
            learner.goto(link,wait_until='networkidle')
            expect(learner.get_by_role('heading',name='Precision player')).to_be_visible()
            expect(learner.locator('.result-row').first).to_contain_text('nudge used')
            expect(learner.locator('.result-rewards')).to_contain_text('+470 XP')
            expect(learner.locator('.achievement-strip')).to_contain_text('Perfect Signal')
            expect(learner.locator('.achievement-strip')).to_contain_text('Combo ×5')
            expect(learner.locator('.achievement-strip')).to_contain_text('Curious Mind')
            check('Saved result replay preserves the trainee\'s hint choice and XP award')
            learner.set_viewport_size({'width':390,'height':844})
            check('Trainee result review fits a narrow mobile screen without horizontal overflow',learner.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))

            expect(trainer.locator('.assignment-card')).to_contain_text('Completed',timeout=15000)
            expect(trainer.locator('.assignment-card')).to_contain_text('100%',timeout=15000)
            expect(trainer.locator('.assignment-card')).to_contain_text('470 XP',timeout=15000)
            expect(trainer.locator('.xp-ladder')).to_contain_text('Studio QA Trainee',timeout=15000)
            expect(trainer.locator('.xp-ladder')).to_contain_text('LEVEL 1 · First Step',timeout=15000)
            expect(trainer.locator('.xp-ladder')).to_contain_text('470 / 500 XP to Explorer',timeout=15000)
            check('Trainer dashboard and XP ladder receive the trainee result live')
            screenshot('trainer-live-result',trainer)

            trainer.get_by_role('button',name='Assign a challenge').click()
            trainer.locator('#assignment-activity').select_option('quiz-product')
            trainer.locator('#assignment-form [type="submit"]').click()
            expect(trainer.locator('.assignment-card')).to_have_count(2)
            product_assignment=trainer.locator('.assignment-card').filter(has_text='Product Knowledge Check')
            expect(product_assignment).to_have_count(1)
            product_assignment.get_by_role('button',name='Create learner links').click()
            second_link=trainer.locator('.private-link-row a').get_attribute('href')
            trainer.locator('#trainer-dialog [data-action="dialog-close"]').click()
            learner_two=context.new_page();learner_two.set_default_timeout(15000);learner_two.on('pageerror',lambda error:errors.append(str(error)))
            submitted_bodies=[]
            def capture_learner_submission(request):
                if request.url.endswith('/api/activities/learner/submit'):submitted_bodies.append(request.post_data or '')
            learner_two.on('request',capture_learner_submission)
            learner_two.goto(second_link,wait_until='networkidle')
            expect(learner_two.get_by_role('heading',name='Product Knowledge Check')).to_be_visible()
            learner_two.set_viewport_size({'width':390,'height':844})
            learner_two.get_by_role('button',name='Jump to challenge').click()
            second_correct_choices=[0,1,2,1,1]
            for index,choice in enumerate(second_correct_choices):
                learner_two.locator('.answer-option').nth(choice).click()
                learner_two.locator('.confidence-check input[value="confident"]').check()
                if index==0:
                    check('The optional confidence check fits a phone screen without horizontal overflow',learner_two.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
                    screenshot('confidence-check-mobile',learner_two,full_page=False)
                action='Finish challenge' if index==len(second_correct_choices)-1 else 'Next round'
                learner_two.get_by_role('button',name=re.compile(action)).click()
            expect(learner_two.locator('.score-orbit')).to_contain_text('80')
            expect(learner_two.locator('.result-rewards')).to_contain_text('+400 XP')
            expect(learner_two.locator('.skill-signals')).to_contain_text('Product accuracy')
            expect(learner_two.locator('.confidence-reflection')).to_contain_text('You felt sure on 5 rounds and got 4 right.')
            expect(learner_two.locator('.confidence-coaching')).to_contain_text('1 confident miss')
            check('The confidence reflection remains readable on a phone',learner_two.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('confidence-reflection-mobile',learner_two,full_page=False)
            assert len(submitted_bodies)==1
            confidence_payload=json.loads(submitted_bodies[0])
            assert 'confidence' not in confidence_payload and all('confidence' not in answer for answer in confidence_payload['answers'])
            check('Optional confidence ratings create a private calibration reflection and never enter the quiz submission')
            review_before=json.loads(owner.call('state')['text'])
            expect(learner_two.locator('[data-action="missed-practice-start"]')).to_contain_text('Practice 1 missed round')
            learner_two.set_viewport_size({'width':390,'height':844})
            learner_two.locator('[data-action="missed-practice-start"]').click()
            expect(learner_two.locator('.missed-practice-card')).to_be_visible()
            expect(learner_two.locator('.missed-practice-answer')).to_have_count(0)
            check('Missed-round active recall fits a phone screen without horizontal overflow',learner_two.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            screenshot('missed-practice-mobile',learner_two,full_page=False)
            learner_two.get_by_role('button',name='Reveal the stronger move').click()
            expect(learner_two.locator('.missed-practice-answer')).to_be_visible()
            screenshot('missed-practice-reveal-mobile',learner_two,full_page=False)
            check('A wrong round becomes private active recall before its coaching answer is revealed')
            learner_two.get_by_role('button',name='Give it one more look').click()
            expect(learner_two.locator('.missed-practice')).to_contain_text('ONE MORE LOOK')
            learner_two.get_by_role('button',name='Reveal the stronger move').click()
            learner_two.get_by_role('button',name='I can explain it').click()
            expect(learner_two.locator('.missed-practice-complete')).to_contain_text('1 idea feels clearer.')
            expect(learner_two.locator('.missed-practice-complete')).to_contain_text('saved score and XP stayed exactly the same')
            check('The completed private practice recap also fits a phone screen',learner_two.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
            learner_two.get_by_role('button',name='Back to saved result').click()
            expect(learner_two.locator('.score-orbit')).to_contain_text('80')
            expect(learner_two.locator('.result-rewards')).to_contain_text('+400 XP')
            learner_two.set_viewport_size({'width':1440,'height':1000})
            expect(trainer.locator('.xp-ladder')).to_contain_text('870 XP',timeout=15000)
            review_after=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:assert review_after[key]==review_before[key],f'private second-chance study changed {key}'
            check('Optional retry practice adds no quiz submission, Academy grade, attendance edit, or XP')
            learner_two.reload(wait_until='networkidle')
            expect(learner_two.locator('.score-orbit')).to_contain_text('80')
            expect(learner_two.locator('.result-rewards')).to_contain_text('+400 XP')
            expect(learner_two.locator('.confidence-reflection')).to_have_count(0)
            expect(learner_two.locator('[data-action="missed-practice-start"]')).to_contain_text('Practice 1 missed round')
            check('A saved result can start the same optional study loop again without creating another attempt')
            expect(learner_two.locator('.achievement-strip')).to_contain_text('Independent Thinker')
            expect(trainer.locator('.xp-ladder')).to_contain_text('870 XP',timeout=15000)
            trainer.locator('#filter-batch').select_option(batch_data['records'][0]['id'])
            expect(trainer.locator('.classroom-pulse')).to_contain_text('2 completed challenges',timeout=15000)
            expect(trainer.locator('.pulse-skill.is-focus')).to_be_visible()
            expect(trainer.locator('.pulse-trend').first).to_be_visible(timeout=15000)
            expect(trainer.locator('.pulse-trend').first).to_contain_text('pts since first try')
            next_mission=trainer.locator('.pulse-next [data-action="live-room"]')
            expect(next_mission).to_be_visible()
            recommended_id=next_mission.get_attribute('data-activity')
            next_mission.click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            expect(trainer.locator('#room-activity')).to_have_value(recommended_id)
            trainer.locator('#live-room-form').get_by_role('button',name='Cancel').click()
            spaced_review=trainer.locator('.pulse-next [data-action="plan-spaced-review"]')
            expect(spaced_review).to_be_visible()
            expect(spaced_review).to_have_attribute('data-activity',recommended_id)
            review_skill=spaced_review.get_attribute('data-focus')
            session_count=trainer.locator('.session-plan-card').count()
            spaced_review.click()
            expect(trainer.locator('#session-plan-form')).to_be_visible()
            expect(trainer.locator('#plan-batch')).to_have_value(batch_data['records'][0]['id'])
            expect(trainer.locator('#plan-activity')).to_have_value(recommended_id)
            expect(trainer.locator('#plan-focus')).to_have_value(review_skill)
            expect(trainer.locator('#plan-review-spacing')).to_have_value('2')
            expect(trainer.locator('#plan-date')).to_have_value('2026-10-08')
            screenshot('spaced-review-planner',trainer,full_page=False)
            trainer.locator('#plan-review-spacing').select_option('3')
            expect(trainer.locator('#plan-date')).to_have_value('2026-10-11')
            expect(trainer.locator('#plan-title')).to_have_value(re.compile('3 sessions'))
            expect(trainer.locator('#plan-date').locator('xpath=ancestor::div[contains(@class,"field")]')).to_contain_text('after 3 scheduled sessions')
            trainer.locator('#session-plan-form').get_by_role('button',name='Cancel').click()
            expect(trainer.locator('.session-plan-card')).to_have_count(session_count)
            spaced_review.click()
            expect(trainer.locator('#plan-date')).to_have_value('2026-10-08')
            records_before_spaced_save=json.loads(owner.call('state')['text'])
            trainer.locator('#session-plan-form [type="submit"]').click()
            expect(trainer.locator('.session-plan-card').filter(has_text='Spaced review')).to_be_visible(timeout=15000)
            expect(trainer.locator('.session-plan-card')).to_have_count(session_count+1)
            trainer_peer.reload(wait_until='domcontentloaded')
            expect(trainer_peer.locator('.session-plan-card').filter(has_text='Spaced review')).to_be_visible(timeout=15000)
            records_after_spaced_save=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:
                assert records_after_spaced_save[key]==records_before_spaced_save[key],f'spaced review planning changed {key}'
            check('The cohort pulse recommends and saves a spaced review to both trainers’ shared board while leaving batches, trainees, grades and attendance untouched')
            trainer.evaluate('''() => {
              const NativeDate=window.Date;
              window.__studioNativeDate=NativeDate;
              window.Date=class extends NativeDate {
                constructor(...args){super(...(args.length?args:['2026-10-08T12:00:00']));}
                static now(){return new NativeDate('2026-10-08T12:00:00').getTime();}
              };
            }''')
            trainer.locator('#filter-batch').select_option(batch_data['records'][0]['id'])
            spaced_card=trainer.locator('.session-plan-card').filter(has_text='Spaced review')
            expect(spaced_card.locator('.session-assign-button')).to_be_visible()
            spaced_card.locator('.session-assign-button').click()
            trainer.evaluate('''() => { window.Date=window.__studioNativeDate; delete window.__studioNativeDate; }''')
            trainer.locator('#filter-batch').select_option('')
            expect(trainer.locator('#dialog-title')).to_have_text('Assign the spaced review')
            expect(trainer.locator('#assignment-batch')).to_have_value(batch_data['records'][0]['id'])
            expect(trainer.locator('#assignment-activity')).to_have_value(recommended_id)
            expect(trainer.locator('#assignment-due')).to_have_value('2026-10-08')
            expect(trainer.locator('.studio-assignment-note strong')).to_contain_text('Review day')
            trainer.locator('#assignment-form').get_by_role('button',name='Cancel').click()
            records_after_cancelled_review=json.loads(owner.call('state')['text'])
            for key in ['batches','trainees','assessments','daily_attendance']:
                assert records_after_cancelled_review[key]==records_after_spaced_save[key],f'opening/cancelling spaced review changed {key}'
            check('A Class Pulse spaced-review plan becomes its focused, due-dated private quiz on review day; cancelling it makes no data changes')
            product_assignment=trainer.locator('.assignment-card').filter(has_text='Product Knowledge Check')
            expect(product_assignment.locator('.practice-signal')).to_contain_text('Product accuracy')
            product_assignment.get_by_role('button',name=re.compile('Assign Trust & Ethics')).click()
            expect(trainer.locator('#assignment-form')).to_be_visible()
            expect(trainer.locator('#assignment-activity')).to_have_value('quiz-trust')
            expect(trainer.locator('#roster-list input[type="checkbox"]:checked')).to_have_count(1)
            trainer.locator('#assignment-form').get_by_role('button',name='Cancel').click()
            check('Quiz outcomes produce a private skill signal and a one-click targeted follow-up for that trainee')
            expect(trainer.locator('.xp-ladder')).to_contain_text('LEVEL 2 · Explorer',timeout=15000)
            expect(trainer.locator('.xp-ladder')).to_contain_text('370 / 1000 XP to Navigator',timeout=15000)
            check('Multiple classroom challenges accumulate XP, achievements and learner levels')
            trainer.get_by_role('button',name='Create a challenge').click()
            expect(trainer.locator('#custom-challenge-form')).to_be_visible()
            trainer.locator('#custom-challenge-form [name="title"]').fill('Cohort Opening Lab')
            trainer.locator('#custom-challenge-form [name="category"]').fill('Client discovery')
            trainer.locator('#custom-challenge-form [name="description"]').fill('Practice curiosity before making a recommendation.')
            ai_requests=[]
            def mock_ai_draft(route):
                ai_requests.append(route.request.post_data_json)
                generated={'questions':[{'prompt':f'A client opens with a broad goal. What is the best next move, round {index+1}?','options':['Send a generic recommendation.','Ask one focused question and listen.','Promise an outcome before checking details.','Choose the client priority for them.'],'answer':1,'skill':'discovery','hint':'Start by learning what matters most.','explanation':'A focused question uncovers the client goal before you recommend the next step.'} for index in range(3)],'study_cards':[{'front':'What comes before a recommendation?','back':'Understand the client goal and priorities first.'}],'source':'ai'}
                route.fulfill(status=200,content_type='application/json',body=json.dumps(generated))
            trainer.route('**/api/ai',mock_ai_draft)
            trainer.locator('#custom-ai-round-count').select_option('3')
            trainer.locator('#custom-ai-notes').fill('Practice open questions and listening before recommending.')
            trainer.locator('[data-action="custom-ai-draft"]').click()
            expect(trainer.locator('#custom-ai-status')).to_contain_text('Check the consent box')
            check('AI lesson notes are not sent unless the trainer explicitly consents')
            assert not ai_requests
            trainer.locator('#custom-ai-consent').check()
            trainer.locator('[data-action="custom-ai-draft"]').click()
            expect(trainer.locator('#custom-ai-status')).to_contain_text('Review every answer',timeout=10000)
            expect(trainer.locator('[data-custom-question]')).to_have_count(3)
            expect(trainer.locator('[data-custom-study]')).to_have_count(1)
            expect(trainer.locator('[data-custom-question]').first.locator('[name="prompt"]')).to_have_value(re.compile('broad goal'))
            check('AI drafts exact-count classroom scenarios and recall cards into the editable, unsaved challenge builder')
            assert len(ai_requests)==1 and ai_requests[0]['consent'] is True
            assert ai_requests[0]['lesson_notes']=='Practice open questions and listening before recommending.'
            assert 'Studio QA Trainee' not in json.dumps(ai_requests[0]) and 'studio-admin@example.test' not in json.dumps(ai_requests[0])
            screenshot('custom-ai-draft',trainer)
            trainer.get_by_role('button',name=re.compile('Add a round')).click()
            expect(trainer.locator('[data-custom-question]')).to_have_count(4)
            trainer.locator('[data-custom-question]').nth(3).get_by_role('button',name='Remove round').click()
            expect(trainer.locator('[data-custom-question]')).to_have_count(3)
            for round_index,card in enumerate(trainer.locator('[data-custom-question]').all()):
                card.locator('[name="prompt"]').fill(f'A new client opens with a broad request. What should you do first? Round {round_index+1}.')
                for option_index,option in enumerate(['Send every available listing.','Ask a focused question and listen.','Promise the outcome they want.','Choose the priority for them.']):
                    card.locator(f'[name="option_{option_index}"]').fill(option)
                card.locator('[name="answer"]').select_option('1')
                card.locator('[name="skill"]').select_option('discovery')
                card.locator('[name="hint"]').fill('First learn what prompted the client to reach out.')
                card.locator('[name="explanation"]').fill('A focused open question helps you understand the client before recommending an option.')
            trainer.get_by_role('button',name=re.compile('Add a recall card')).click()
            expect(trainer.locator('[data-custom-study]')).to_have_count(2)
            trainer.locator('[data-custom-study]').nth(1).get_by_role('button',name='Remove card').click()
            card=trainer.locator('[data-custom-study]').first
            card.locator('[name="front"]').fill('What comes before a recommendation?')
            card.locator('[name="back"]').fill('Learn the client goal, timing, and priorities first.')
            screenshot('custom-challenge-builder',trainer)
            trainer.locator('#custom-challenge-form [type="submit"]').click()
            custom_tile=trainer.locator('.quiz-tile').filter(has=trainer.get_by_role('heading',name='Cohort Opening Lab'))
            expect(custom_tile).to_be_visible(timeout=10000)
            expect(trainer.locator('.quiz-tile')).to_have_count(9)
            custom_tile.get_by_role('button',name='Host live').click()
            expect(trainer.locator('#live-room-form')).to_be_visible()
            expect(trainer.locator('#room-activity')).to_have_value(custom_tile.get_attribute('data-activity-id') or '')
            trainer.locator('#live-room-form [name="phone_enabled"]').check()
            trainer.locator('#live-room-form [type="submit"]').click()
            expect(trainer.locator('.room-title-line h1')).to_have_text('Cohort Opening Lab')
            expect(trainer.locator('.room-join-panel')).to_be_visible()
            trainer.reload(wait_until='networkidle')
            expect(trainer.get_by_role('button',name=re.compile('Resume live room'))).to_be_visible(timeout=10000)
            custom_tile.get_by_role('button',name='Assign to class').click()
            expect(trainer.locator('#assignment-activity')).to_have_value(custom_tile.get_attribute('data-activity-id') or '')
            trainer.locator('#assignment-form [type="submit"]').click()
            custom_assignment=trainer.locator('.assignment-card').filter(has_text='Cohort Opening Lab')
            expect(custom_assignment).to_be_visible(timeout=10000)
            custom_assignment.get_by_role('button',name='Create learner links').click()
            custom_link=trainer.locator('.private-link-row a').get_attribute('href')
            trainer.locator('#trainer-dialog [data-action="dialog-close"]').click()
            custom_learner=context.new_page();custom_learner.set_default_timeout(15000);custom_learner.on('pageerror',lambda error:errors.append(str(error)))
            custom_learner.goto(custom_link,wait_until='networkidle')
            expect(custom_learner.get_by_role('heading',name='Cohort Opening Lab')).to_be_visible()
            custom_learner.get_by_role('button',name='Study warm-up').click()
            custom_learner.get_by_role('button',name='Reveal takeaway').click()
            expect(custom_learner.locator('.study-card')).to_contain_text('Learn the client goal')
            custom_learner.get_by_role('button',name='Got it').click()
            custom_learner.get_by_role('button',name='Start challenge').click()
            for index,choice in enumerate([0,1,1]):
                custom_learner.locator('.answer-option').nth(choice).click()
                custom_learner.get_by_role('button',name='Finish challenge' if index==2 else 'Next round').click()
            expect(custom_learner.locator('.score-orbit')).to_contain_text('67')
            check('Trainer-built challenge and active-recall cards work through the same private learner flow')
            trainer.locator('.quiz-tile').filter(has=trainer.get_by_role('heading',name='Cohort Opening Lab')).get_by_role('button',name='Archive challenge').click()
            expect(trainer.locator('.quiz-tile')).to_have_count(8,timeout=10000)
            expect(custom_assignment).to_contain_text('ARCHIVED VERSION · EXISTING RESULTS KEPT')
            expect(custom_assignment).to_contain_text('67%',timeout=10000)
            trainer.get_by_role('button',name=re.compile('Resume live room')).click()
            trainer.locator('.live-room-resume-row').filter(has_text='Cohort Opening Lab').click()
            expect(trainer.locator('.room-title-line h1')).to_have_text('Cohort Opening Lab')
            expect(trainer.locator('.room-question h2')).to_contain_text('broad request')
            check('An archived custom challenge still resumes from its frozen owner-only live-room snapshot after a reload')
            trainer.get_by_role('button',name='End phone room').click()
            custom_learner.reload(wait_until='networkidle')
            expect(custom_learner.locator('.score-orbit')).to_contain_text('67')
            check('Archiving removes a custom challenge from new setup but preserves submitted results and learner replay')
            check('No uncaught browser JavaScript errors',not errors)
            if errors: raise AssertionError('; '.join(errors))
            browser.close()
    finally:
        server.terminate()
        try: server.wait(timeout=5)
        except subprocess.TimeoutExpired: server.kill();server.wait(timeout=5)
